// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/mwitkow/go-proto-validators/validator.proto

package validator

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FieldValidator struct {
	// Uses a Golang RE2-syntax regex to match the field contents.
	Regex *string `protobuf:"bytes,1,opt,name=regex" json:"regex,omitempty"`
	// Field value of integer strictly greater than this value.
	IntGt *int64 `protobuf:"varint,2,opt,name=int_gt,json=intGt" json:"int_gt,omitempty"`
	// Field value of integer strictly smaller than this value.
	IntLt *int64 `protobuf:"varint,3,opt,name=int_lt,json=intLt" json:"int_lt,omitempty"`
	// Used for nested message types, requires that the message type exists.
	MsgExists *bool `protobuf:"varint,4,opt,name=msg_exists,json=msgExists" json:"msg_exists,omitempty"`
	// Human error specifies a user-customizable error that is visible to the user.
	HumanError *string `protobuf:"bytes,5,opt,name=human_error,json=humanError" json:"human_error,omitempty"`
	// Field value of double strictly greater than this value.
	// Note that this value can only take on a valid floating point
	// value. Use together with float_epsilon if you need something more specific.
	FloatGt *float64 `protobuf:"fixed64,6,opt,name=float_gt,json=floatGt" json:"float_gt,omitempty"`
	// Field value of double strictly smaller than this value.
	// Note that this value can only take on a valid floating point
	// value. Use together with float_epsilon if you need something more specific.
	FloatLt *float64 `protobuf:"fixed64,7,opt,name=float_lt,json=floatLt" json:"float_lt,omitempty"`
	// Field value of double describing the epsilon within which
	// any comparison should be considered to be true. For example,
	// when using float_gt = 0.35, using a float_epsilon of 0.05
	// would mean that any value above 0.30 is acceptable. It can be
	// thought of as a {float_value_condition} +- {float_epsilon}.
	// If unset, no correction for floating point inaccuracies in
	// comparisons will be attempted.
	FloatEpsilon *float64 `protobuf:"fixed64,8,opt,name=float_epsilon,json=floatEpsilon" json:"float_epsilon,omitempty"`
	// Floating-point value compared to which the field content should be greater or equal.
	FloatGte *float64 `protobuf:"fixed64,9,opt,name=float_gte,json=floatGte" json:"float_gte,omitempty"`
	// Floating-point value compared to which the field content should be smaller or equal.
	FloatLte *float64 `protobuf:"fixed64,10,opt,name=float_lte,json=floatLte" json:"float_lte,omitempty"`
	// Used for string fields, requires the string to be not empty (i.e different from "").
	StringNotEmpty *bool `protobuf:"varint,11,opt,name=string_not_empty,json=stringNotEmpty" json:"string_not_empty,omitempty"`
	// Repeated field with at least this number of elements.
	RepeatedCountMin *int64 `protobuf:"varint,12,opt,name=repeated_count_min,json=repeatedCountMin" json:"repeated_count_min,omitempty"`
	// Repeated field with at most this number of elements.
	RepeatedCountMax *int64 `protobuf:"varint,13,opt,name=repeated_count_max,json=repeatedCountMax" json:"repeated_count_max,omitempty"`
	// Field value of length greater than this value.
	LengthGt *int64 `protobuf:"varint,14,opt,name=length_gt,json=lengthGt" json:"length_gt,omitempty"`
	// Field value of length smaller than this value.
	LengthLt *int64 `protobuf:"varint,15,opt,name=length_lt,json=lengthLt" json:"length_lt,omitempty"`
	// Field value of integer strictly equal this value.
	LengthEq *int64 `protobuf:"varint,16,opt,name=length_eq,json=lengthEq" json:"length_eq,omitempty"`
	// Requires that the value is in the enum.
	IsInEnum *bool `protobuf:"varint,17,opt,name=is_in_enum,json=isInEnum" json:"is_in_enum,omitempty"`
	// Ensures that a string value is in UUID format.
	// uuid_ver specifies the valid UUID versions. Valid values are: 0-5.
	// If uuid_ver is 0 all UUID versions are accepted.
	UuidVer              *int32   `protobuf:"varint,18,opt,name=uuid_ver,json=uuidVer" json:"uuid_ver,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FieldValidator) Reset()         { *m = FieldValidator{} }
func (m *FieldValidator) String() string { return proto.CompactTextString(m) }
func (*FieldValidator) ProtoMessage()    {}
func (*FieldValidator) Descriptor() ([]byte, []int) {
	return fileDescriptor_28cf2c7f5f3c12e2, []int{0}
}

func (m *FieldValidator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldValidator.Unmarshal(m, b)
}
func (m *FieldValidator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldValidator.Marshal(b, m, deterministic)
}
func (m *FieldValidator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldValidator.Merge(m, src)
}
func (m *FieldValidator) XXX_Size() int {
	return xxx_messageInfo_FieldValidator.Size(m)
}
func (m *FieldValidator) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldValidator.DiscardUnknown(m)
}

var xxx_messageInfo_FieldValidator proto.InternalMessageInfo

func (m *FieldValidator) GetRegex() string {
	if m != nil && m.Regex != nil {
		return *m.Regex
	}
	return ""
}

func (m *FieldValidator) GetIntGt() int64 {
	if m != nil && m.IntGt != nil {
		return *m.IntGt
	}
	return 0
}

func (m *FieldValidator) GetIntLt() int64 {
	if m != nil && m.IntLt != nil {
		return *m.IntLt
	}
	return 0
}

func (m *FieldValidator) GetMsgExists() bool {
	if m != nil && m.MsgExists != nil {
		return *m.MsgExists
	}
	return false
}

func (m *FieldValidator) GetHumanError() string {
	if m != nil && m.HumanError != nil {
		return *m.HumanError
	}
	return ""
}

func (m *FieldValidator) GetFloatGt() float64 {
	if m != nil && m.FloatGt != nil {
		return *m.FloatGt
	}
	return 0
}

func (m *FieldValidator) GetFloatLt() float64 {
	if m != nil && m.FloatLt != nil {
		return *m.FloatLt
	}
	return 0
}

func (m *FieldValidator) GetFloatEpsilon() float64 {
	if m != nil && m.FloatEpsilon != nil {
		return *m.FloatEpsilon
	}
	return 0
}

func (m *FieldValidator) GetFloatGte() float64 {
	if m != nil && m.FloatGte != nil {
		return *m.FloatGte
	}
	return 0
}

func (m *FieldValidator) GetFloatLte() float64 {
	if m != nil && m.FloatLte != nil {
		return *m.FloatLte
	}
	return 0
}

func (m *FieldValidator) GetStringNotEmpty() bool {
	if m != nil && m.StringNotEmpty != nil {
		return *m.StringNotEmpty
	}
	return false
}

func (m *FieldValidator) GetRepeatedCountMin() int64 {
	if m != nil && m.RepeatedCountMin != nil {
		return *m.RepeatedCountMin
	}
	return 0
}

func (m *FieldValidator) GetRepeatedCountMax() int64 {
	if m != nil && m.RepeatedCountMax != nil {
		return *m.RepeatedCountMax
	}
	return 0
}

func (m *FieldValidator) GetLengthGt() int64 {
	if m != nil && m.LengthGt != nil {
		return *m.LengthGt
	}
	return 0
}

func (m *FieldValidator) GetLengthLt() int64 {
	if m != nil && m.LengthLt != nil {
		return *m.LengthLt
	}
	return 0
}

func (m *FieldValidator) GetLengthEq() int64 {
	if m != nil && m.LengthEq != nil {
		return *m.LengthEq
	}
	return 0
}

func (m *FieldValidator) GetIsInEnum() bool {
	if m != nil && m.IsInEnum != nil {
		return *m.IsInEnum
	}
	return false
}

func (m *FieldValidator) GetUuidVer() int32 {
	if m != nil && m.UuidVer != nil {
		return *m.UuidVer
	}
	return 0
}

type OneofValidator struct {
	// Require that one of the oneof fields is set.
	Required             *bool    `protobuf:"varint,1,opt,name=required" json:"required,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OneofValidator) Reset()         { *m = OneofValidator{} }
func (m *OneofValidator) String() string { return proto.CompactTextString(m) }
func (*OneofValidator) ProtoMessage()    {}
func (*OneofValidator) Descriptor() ([]byte, []int) {
	return fileDescriptor_28cf2c7f5f3c12e2, []int{1}
}

func (m *OneofValidator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OneofValidator.Unmarshal(m, b)
}
func (m *OneofValidator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OneofValidator.Marshal(b, m, deterministic)
}
func (m *OneofValidator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OneofValidator.Merge(m, src)
}
func (m *OneofValidator) XXX_Size() int {
	return xxx_messageInfo_OneofValidator.Size(m)
}
func (m *OneofValidator) XXX_DiscardUnknown() {
	xxx_messageInfo_OneofValidator.DiscardUnknown(m)
}

var xxx_messageInfo_OneofValidator proto.InternalMessageInfo

func (m *OneofValidator) GetRequired() bool {
	if m != nil && m.Required != nil {
		return *m.Required
	}
	return false
}

var E_Field = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*FieldValidator)(nil),
	Field:         65020,
	Name:          "validator.field",
	Tag:           "bytes,65020,opt,name=field",
	Filename:      "github.com/mwitkow/go-proto-validators/validator.proto",
}

var E_Oneof = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.OneofOptions)(nil),
	ExtensionType: (*OneofValidator)(nil),
	Field:         65021,
	Name:          "validator.oneof",
	Tag:           "bytes,65021,opt,name=oneof",
	Filename:      "github.com/mwitkow/go-proto-validators/validator.proto",
}

func init() {
	proto.RegisterType((*FieldValidator)(nil), "validator.FieldValidator")
	proto.RegisterType((*OneofValidator)(nil), "validator.OneofValidator")
	proto.RegisterExtension(E_Field)
	proto.RegisterExtension(E_Oneof)
}

func init() {
	proto.RegisterFile("github.com/mwitkow/go-proto-validators/validator.proto", fileDescriptor_28cf2c7f5f3c12e2)
}

var fileDescriptor_28cf2c7f5f3c12e2 = []byte{
	// 498 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0xc1, 0x6f, 0xd3, 0x30,
	0x14, 0xc6, 0x15, 0xb6, 0x6e, 0xa9, 0xbb, 0x95, 0x62, 0x81, 0xe4, 0x0d, 0x26, 0xa2, 0x71, 0xc9,
	0x61, 0x4b, 0x25, 0x0e, 0x1c, 0x38, 0x82, 0x42, 0x85, 0x54, 0x18, 0xca, 0x61, 0x07, 0x2e, 0x51,
	0xd6, 0xbc, 0xba, 0x16, 0x8e, 0x9d, 0xda, 0x2f, 0x5b, 0xf9, 0xeb, 0xf8, 0xc3, 0x00, 0x09, 0xd9,
	0x21, 0x6d, 0x26, 0xf5, 0xd6, 0xf7, 0xfd, 0x5e, 0xbf, 0xf7, 0xfc, 0xf4, 0x85, 0xbc, 0xe3, 0x02,
	0x57, 0xcd, 0x5d, 0xb2, 0xd0, 0xd5, 0xb4, 0x7a, 0x10, 0xf8, 0x43, 0x3f, 0x4c, 0xb9, 0xbe, 0xae,
	0x8d, 0x46, 0x7d, 0x7d, 0x5f, 0x48, 0x51, 0x16, 0xa8, 0x8d, 0x9d, 0x6e, 0x7f, 0x26, 0x1e, 0xd1,
	0xe1, 0x56, 0x38, 0x8f, 0xb8, 0xd6, 0x5c, 0xc2, 0xd4, 0x83, 0xbb, 0x66, 0x39, 0x2d, 0xc1, 0x2e,
	0x8c, 0xa8, 0xb7, 0xcd, 0x97, 0xbf, 0x0e, 0xc9, 0xf8, 0x93, 0x00, 0x59, 0xde, 0x76, 0x7f, 0xa2,
	0xcf, 0xc9, 0xc0, 0x00, 0x87, 0x0d, 0x0b, 0xa2, 0x20, 0x1e, 0x66, 0x6d, 0x41, 0x5f, 0x90, 0x23,
	0xa1, 0x30, 0xe7, 0xc8, 0x9e, 0x44, 0x41, 0x7c, 0x90, 0x0d, 0x84, 0xc2, 0x19, 0x76, 0xb2, 0x44,
	0x76, 0xb0, 0x95, 0xe7, 0x48, 0x2f, 0x08, 0xa9, 0x2c, 0xcf, 0x61, 0x23, 0x2c, 0x5a, 0x76, 0x18,
	0x05, 0x71, 0x98, 0x0d, 0x2b, 0xcb, 0x53, 0x2f, 0xd0, 0xd7, 0x64, 0xb4, 0x6a, 0xaa, 0x42, 0xe5,
	0x60, 0x8c, 0x36, 0x6c, 0xe0, 0x07, 0x11, 0x2f, 0xa5, 0x4e, 0xa1, 0x67, 0x24, 0x5c, 0x4a, 0x5d,
	0xf8, 0x79, 0x47, 0x51, 0x10, 0x07, 0xd9, 0xb1, 0xaf, 0x67, 0xb8, 0x43, 0x12, 0xd9, 0x71, 0x0f,
	0xcd, 0x91, 0xbe, 0x21, 0xa7, 0x2d, 0x82, 0xda, 0x0a, 0xa9, 0x15, 0x0b, 0x3d, 0x3f, 0xf1, 0x62,
	0xda, 0x6a, 0xf4, 0x25, 0x19, 0x76, 0xd6, 0xc0, 0x86, 0xbe, 0x21, 0xfc, 0xef, 0x0d, 0x3b, 0x28,
	0x11, 0x18, 0xe9, 0xc1, 0x39, 0x02, 0x8d, 0xc9, 0xc4, 0xa2, 0x11, 0x8a, 0xe7, 0x4a, 0x63, 0x0e,
	0x55, 0x8d, 0x3f, 0xd9, 0xc8, 0x3f, 0x6d, 0xdc, 0xea, 0x5f, 0x35, 0xa6, 0x4e, 0xa5, 0x57, 0x84,
	0x1a, 0xa8, 0xa1, 0x40, 0x28, 0xf3, 0x85, 0x6e, 0x14, 0xe6, 0x95, 0x50, 0xec, 0xc4, 0x5f, 0x68,
	0xd2, 0x91, 0x8f, 0x0e, 0x7c, 0x11, 0x6a, 0x5f, 0x77, 0xb1, 0x61, 0xa7, 0xfb, 0xba, 0x8b, 0x8d,
	0x5b, 0x51, 0x82, 0xe2, 0xb8, 0x72, 0xb7, 0x19, 0xfb, 0xa6, 0xb0, 0x15, 0x66, 0xd8, 0x83, 0x12,
	0xd9, 0xd3, 0x3e, 0x9c, 0xf7, 0x21, 0xac, 0xd9, 0xa4, 0x0f, 0xd3, 0x35, 0x7d, 0x45, 0x88, 0xb0,
	0xb9, 0x50, 0x39, 0xa8, 0xa6, 0x62, 0xcf, 0xfc, 0xb3, 0x42, 0x61, 0x3f, 0xab, 0x54, 0x35, 0x95,
	0x3b, 0x7a, 0xd3, 0x88, 0x32, 0xbf, 0x07, 0xc3, 0x68, 0x14, 0xc4, 0x83, 0xec, 0xd8, 0xd5, 0xb7,
	0x60, 0x2e, 0xaf, 0xc8, 0xf8, 0x46, 0x81, 0x5e, 0xee, 0x02, 0x74, 0x4e, 0x42, 0x03, 0xeb, 0x46,
	0x18, 0x28, 0x7d, 0x86, 0xc2, 0x6c, 0x5b, 0xbf, 0xff, 0x46, 0x06, 0x4b, 0x17, 0x37, 0x7a, 0x91,
	0xb4, 0xd9, 0x4c, 0xba, 0x6c, 0x26, 0x3e, 0x86, 0x37, 0x35, 0x0a, 0xad, 0x2c, 0xfb, 0xf3, 0xdb,
	0xe5, 0x69, 0xf4, 0xf6, 0x2c, 0xd9, 0xc5, 0xfb, 0x71, 0x4e, 0xb3, 0xd6, 0xc8, 0x39, 0x6a, 0x37,
	0x7f, 0x8f, 0xa3, 0xdf, 0xab, 0x73, 0xfc, 0xbb, 0xc7, 0xf1, 0xf1, 0xe2, 0x59, 0x6b, 0xf4, 0x61,
	0xf4, 0x7d, 0xf7, 0x09, 0xfd, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x15, 0x68, 0x80, 0x3f, 0x86, 0x03,
	0x00, 0x00,
}
