// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/governance.proto

package proto

import (
	v1 "code.vegaprotocol.io/go-wallet/internal/proto/oracles/v1"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// A list of possible errors that can cause a proposal to be in state rejected or failed
type ProposalError int32

const (
	// Default value
	ProposalError_PROPOSAL_ERROR_UNSPECIFIED ProposalError = 0
	// The specified close time is too early base on network parameters
	ProposalError_PROPOSAL_ERROR_CLOSE_TIME_TOO_SOON ProposalError = 1
	// The specified close time is too late based on network parameters
	ProposalError_PROPOSAL_ERROR_CLOSE_TIME_TOO_LATE ProposalError = 2
	// The specified enact time is too early based on network parameters
	ProposalError_PROPOSAL_ERROR_ENACT_TIME_TOO_SOON ProposalError = 3
	// The specified enact time is too late based on network parameters
	ProposalError_PROPOSAL_ERROR_ENACT_TIME_TOO_LATE ProposalError = 4
	// The proposer for this proposal as insufficient tokens
	ProposalError_PROPOSAL_ERROR_INSUFFICIENT_TOKENS ProposalError = 5
	// The instrument quote name and base name were the same
	ProposalError_PROPOSAL_ERROR_INVALID_INSTRUMENT_SECURITY ProposalError = 6
	// The proposal has no product
	ProposalError_PROPOSAL_ERROR_NO_PRODUCT ProposalError = 7
	// The specified product is not supported
	ProposalError_PROPOSAL_ERROR_UNSUPPORTED_PRODUCT ProposalError = 8
	// Invalid future maturity timestamp (expect RFC3339)
	ProposalError_PROPOSAL_ERROR_INVALID_FUTURE_PRODUCT_TIMESTAMP ProposalError = 9
	// The product maturity is past
	ProposalError_PROPOSAL_ERROR_PRODUCT_MATURITY_IS_PASSED ProposalError = 10
	// The proposal has no trading mode
	ProposalError_PROPOSAL_ERROR_NO_TRADING_MODE ProposalError = 11
	// The proposal has an unsupported trading mode
	ProposalError_PROPOSAL_ERROR_UNSUPPORTED_TRADING_MODE ProposalError = 12
	// The proposal failed node validation
	ProposalError_PROPOSAL_ERROR_NODE_VALIDATION_FAILED ProposalError = 13
	// A field is missing in a builtin asset source
	ProposalError_PROPOSAL_ERROR_MISSING_BUILTIN_ASSET_FIELD ProposalError = 14
	// The contract address is missing in the ERC20 asset source
	ProposalError_PROPOSAL_ERROR_MISSING_ERC20_CONTRACT_ADDRESS ProposalError = 15
	// The asset identifier is invalid or does not exist on the Vega network
	ProposalError_PROPOSAL_ERROR_INVALID_ASSET ProposalError = 16
	// Proposal terms timestamps are not compatible (Validation < Closing < Enactment)
	ProposalError_PROPOSAL_ERROR_INCOMPATIBLE_TIMESTAMPS ProposalError = 17
	// No risk parameters were specified
	ProposalError_PROPOSAL_ERROR_NO_RISK_PARAMETERS ProposalError = 18
	// Invalid key in update network parameter proposal
	ProposalError_PROPOSAL_ERROR_NETWORK_PARAMETER_INVALID_KEY ProposalError = 19
	// Invalid valid in update network parameter proposal
	ProposalError_PROPOSAL_ERROR_NETWORK_PARAMETER_INVALID_VALUE ProposalError = 20
	// Validation failed for network parameter proposal
	ProposalError_PROPOSAL_ERROR_NETWORK_PARAMETER_VALIDATION_FAILED ProposalError = 21
	// Opening auction duration is less than the network minimum opening auction time
	ProposalError_PROPOSAL_ERROR_OPENING_AUCTION_DURATION_TOO_SMALL ProposalError = 22
	// Opening auction duration is more than the network minimum opening auction time
	ProposalError_PROPOSAL_ERROR_OPENING_AUCTION_DURATION_TOO_LARGE ProposalError = 23
	// Market proposal is missing a liquidity commitment
	ProposalError_PROPOSAL_ERROR_MARKET_MISSING_LIQUIDITY_COMMITMENT ProposalError = 24
	// Market proposal market could not be instantiate in execution
	ProposalError_PROPOSAL_ERROR_COULD_NOT_INSTANTIATE_MARKET ProposalError = 25
	// Market proposal market contained invalid product definition
	ProposalError_PROPOSAL_ERROR_INVALID_FUTURE_PRODUCT ProposalError = 26
	// Market proposal is missing commitment amount
	ProposalError_PROPOSAL_ERROR_MISSING_COMMITMENT_AMOUNT ProposalError = 27
	// Market proposal have invalid fee
	ProposalError_PROPOSAL_ERROR_INVALID_FEE_AMOUNT ProposalError = 28
	// Market proposal have invalid shape
	ProposalError_PROPOSAL_ERROR_INVALID_SHAPE ProposalError = 29
	// Market proposal invalid risk parameter
	ProposalError_PROPOSAL_ERROR_INVALID_RISK_PARAMETER ProposalError = 30
	// Proposal was declined because vote didn't reach the majority thershold required
	ProposalError_PROPOSAL_ERROR_MAJORITY_THRESHOLD_NOT_REACHED ProposalError = 31
	// Proposal declined because the participation threshold was not reached
	ProposalError_PROPOSAL_ERROR_PARTICIPATION_THRESHOLD_NOT_REACHED ProposalError = 32
	// Asset proposal invalid asset details
	ProposalError_PROPOSAL_ERROR_INVALID_ASSET_DETAILS ProposalError = 33
)

var ProposalError_name = map[int32]string{
	0:  "PROPOSAL_ERROR_UNSPECIFIED",
	1:  "PROPOSAL_ERROR_CLOSE_TIME_TOO_SOON",
	2:  "PROPOSAL_ERROR_CLOSE_TIME_TOO_LATE",
	3:  "PROPOSAL_ERROR_ENACT_TIME_TOO_SOON",
	4:  "PROPOSAL_ERROR_ENACT_TIME_TOO_LATE",
	5:  "PROPOSAL_ERROR_INSUFFICIENT_TOKENS",
	6:  "PROPOSAL_ERROR_INVALID_INSTRUMENT_SECURITY",
	7:  "PROPOSAL_ERROR_NO_PRODUCT",
	8:  "PROPOSAL_ERROR_UNSUPPORTED_PRODUCT",
	9:  "PROPOSAL_ERROR_INVALID_FUTURE_PRODUCT_TIMESTAMP",
	10: "PROPOSAL_ERROR_PRODUCT_MATURITY_IS_PASSED",
	11: "PROPOSAL_ERROR_NO_TRADING_MODE",
	12: "PROPOSAL_ERROR_UNSUPPORTED_TRADING_MODE",
	13: "PROPOSAL_ERROR_NODE_VALIDATION_FAILED",
	14: "PROPOSAL_ERROR_MISSING_BUILTIN_ASSET_FIELD",
	15: "PROPOSAL_ERROR_MISSING_ERC20_CONTRACT_ADDRESS",
	16: "PROPOSAL_ERROR_INVALID_ASSET",
	17: "PROPOSAL_ERROR_INCOMPATIBLE_TIMESTAMPS",
	18: "PROPOSAL_ERROR_NO_RISK_PARAMETERS",
	19: "PROPOSAL_ERROR_NETWORK_PARAMETER_INVALID_KEY",
	20: "PROPOSAL_ERROR_NETWORK_PARAMETER_INVALID_VALUE",
	21: "PROPOSAL_ERROR_NETWORK_PARAMETER_VALIDATION_FAILED",
	22: "PROPOSAL_ERROR_OPENING_AUCTION_DURATION_TOO_SMALL",
	23: "PROPOSAL_ERROR_OPENING_AUCTION_DURATION_TOO_LARGE",
	24: "PROPOSAL_ERROR_MARKET_MISSING_LIQUIDITY_COMMITMENT",
	25: "PROPOSAL_ERROR_COULD_NOT_INSTANTIATE_MARKET",
	26: "PROPOSAL_ERROR_INVALID_FUTURE_PRODUCT",
	27: "PROPOSAL_ERROR_MISSING_COMMITMENT_AMOUNT",
	28: "PROPOSAL_ERROR_INVALID_FEE_AMOUNT",
	29: "PROPOSAL_ERROR_INVALID_SHAPE",
	30: "PROPOSAL_ERROR_INVALID_RISK_PARAMETER",
	31: "PROPOSAL_ERROR_MAJORITY_THRESHOLD_NOT_REACHED",
	32: "PROPOSAL_ERROR_PARTICIPATION_THRESHOLD_NOT_REACHED",
	33: "PROPOSAL_ERROR_INVALID_ASSET_DETAILS",
}

var ProposalError_value = map[string]int32{
	"PROPOSAL_ERROR_UNSPECIFIED":                         0,
	"PROPOSAL_ERROR_CLOSE_TIME_TOO_SOON":                 1,
	"PROPOSAL_ERROR_CLOSE_TIME_TOO_LATE":                 2,
	"PROPOSAL_ERROR_ENACT_TIME_TOO_SOON":                 3,
	"PROPOSAL_ERROR_ENACT_TIME_TOO_LATE":                 4,
	"PROPOSAL_ERROR_INSUFFICIENT_TOKENS":                 5,
	"PROPOSAL_ERROR_INVALID_INSTRUMENT_SECURITY":         6,
	"PROPOSAL_ERROR_NO_PRODUCT":                          7,
	"PROPOSAL_ERROR_UNSUPPORTED_PRODUCT":                 8,
	"PROPOSAL_ERROR_INVALID_FUTURE_PRODUCT_TIMESTAMP":    9,
	"PROPOSAL_ERROR_PRODUCT_MATURITY_IS_PASSED":          10,
	"PROPOSAL_ERROR_NO_TRADING_MODE":                     11,
	"PROPOSAL_ERROR_UNSUPPORTED_TRADING_MODE":            12,
	"PROPOSAL_ERROR_NODE_VALIDATION_FAILED":              13,
	"PROPOSAL_ERROR_MISSING_BUILTIN_ASSET_FIELD":         14,
	"PROPOSAL_ERROR_MISSING_ERC20_CONTRACT_ADDRESS":      15,
	"PROPOSAL_ERROR_INVALID_ASSET":                       16,
	"PROPOSAL_ERROR_INCOMPATIBLE_TIMESTAMPS":             17,
	"PROPOSAL_ERROR_NO_RISK_PARAMETERS":                  18,
	"PROPOSAL_ERROR_NETWORK_PARAMETER_INVALID_KEY":       19,
	"PROPOSAL_ERROR_NETWORK_PARAMETER_INVALID_VALUE":     20,
	"PROPOSAL_ERROR_NETWORK_PARAMETER_VALIDATION_FAILED": 21,
	"PROPOSAL_ERROR_OPENING_AUCTION_DURATION_TOO_SMALL":  22,
	"PROPOSAL_ERROR_OPENING_AUCTION_DURATION_TOO_LARGE":  23,
	"PROPOSAL_ERROR_MARKET_MISSING_LIQUIDITY_COMMITMENT": 24,
	"PROPOSAL_ERROR_COULD_NOT_INSTANTIATE_MARKET":        25,
	"PROPOSAL_ERROR_INVALID_FUTURE_PRODUCT":              26,
	"PROPOSAL_ERROR_MISSING_COMMITMENT_AMOUNT":           27,
	"PROPOSAL_ERROR_INVALID_FEE_AMOUNT":                  28,
	"PROPOSAL_ERROR_INVALID_SHAPE":                       29,
	"PROPOSAL_ERROR_INVALID_RISK_PARAMETER":              30,
	"PROPOSAL_ERROR_MAJORITY_THRESHOLD_NOT_REACHED":      31,
	"PROPOSAL_ERROR_PARTICIPATION_THRESHOLD_NOT_REACHED": 32,
	"PROPOSAL_ERROR_INVALID_ASSET_DETAILS":               33,
}

func (x ProposalError) String() string {
	return proto.EnumName(ProposalError_name, int32(x))
}

func (ProposalError) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c891e73c7d2524a3, []int{0}
}

// Proposal state transition:
// Open ->
//   - Passed -> Enacted.
//   - Passed -> Failed.
//   - Declined
// Rejected
// Proposal can enter Failed state from any other state
type Proposal_State int32

const (
	// Default value, always invalid
	Proposal_STATE_UNSPECIFIED Proposal_State = 0
	// Proposal enactment has failed - even though proposal has passed, its execution could not be performed
	Proposal_STATE_FAILED Proposal_State = 1
	// Proposal is open for voting
	Proposal_STATE_OPEN Proposal_State = 2
	// Proposal has gained enough support to be executed
	Proposal_STATE_PASSED Proposal_State = 3
	// Proposal wasn't accepted (proposal terms failed validation due to wrong configuration or failing to meet network requirements)
	Proposal_STATE_REJECTED Proposal_State = 4
	// Proposal didn't get enough votes (either failing to gain required participation or majority level)
	Proposal_STATE_DECLINED Proposal_State = 5
	// Proposal enacted
	Proposal_STATE_ENACTED Proposal_State = 6
	// Waiting for node validation of the proposal
	Proposal_STATE_WAITING_FOR_NODE_VOTE Proposal_State = 7
)

var Proposal_State_name = map[int32]string{
	0: "STATE_UNSPECIFIED",
	1: "STATE_FAILED",
	2: "STATE_OPEN",
	3: "STATE_PASSED",
	4: "STATE_REJECTED",
	5: "STATE_DECLINED",
	6: "STATE_ENACTED",
	7: "STATE_WAITING_FOR_NODE_VOTE",
}

var Proposal_State_value = map[string]int32{
	"STATE_UNSPECIFIED":           0,
	"STATE_FAILED":                1,
	"STATE_OPEN":                  2,
	"STATE_PASSED":                3,
	"STATE_REJECTED":              4,
	"STATE_DECLINED":              5,
	"STATE_ENACTED":               6,
	"STATE_WAITING_FOR_NODE_VOTE": 7,
}

func (x Proposal_State) String() string {
	return proto.EnumName(Proposal_State_name, int32(x))
}

func (Proposal_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c891e73c7d2524a3, []int{10, 0}
}

// Vote value
type Vote_Value int32

const (
	// Default value, always invalid
	Vote_VALUE_UNSPECIFIED Vote_Value = 0
	// A vote against the proposal
	Vote_VALUE_NO Vote_Value = 1
	// A vote in favour of the proposal
	Vote_VALUE_YES Vote_Value = 2
)

var Vote_Value_name = map[int32]string{
	0: "VALUE_UNSPECIFIED",
	1: "VALUE_NO",
	2: "VALUE_YES",
}

var Vote_Value_value = map[string]int32{
	"VALUE_UNSPECIFIED": 0,
	"VALUE_NO":          1,
	"VALUE_YES":         2,
}

func (x Vote_Value) String() string {
	return proto.EnumName(Vote_Value_name, int32(x))
}

func (Vote_Value) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c891e73c7d2524a3, []int{11, 0}
}

// Future product configuration
type FutureProduct struct {
	// Future product maturity (ISO8601/RFC3339 timestamp)
	Maturity string `protobuf:"bytes,1,opt,name=maturity,proto3" json:"maturity,omitempty"`
	// Product settlement asset identifier
	SettlementAsset string `protobuf:"bytes,2,opt,name=settlement_asset,json=settlementAsset,proto3" json:"settlement_asset,omitempty"`
	// Product quote name
	QuoteName string `protobuf:"bytes,3,opt,name=quote_name,json=quoteName,proto3" json:"quote_name,omitempty"`
	// The oracle spec describing the oracle data of settlement price
	OracleSpecForSettlementPrice *v1.OracleSpecConfiguration `protobuf:"bytes,5,opt,name=oracle_spec_for_settlement_price,json=oracleSpecForSettlementPrice,proto3" json:"oracle_spec_for_settlement_price,omitempty"`
	// The oracle spec describing the oracle data of trading termination
	OracleSpecForTradingTermination *v1.OracleSpecConfiguration `protobuf:"bytes,6,opt,name=oracle_spec_for_trading_termination,json=oracleSpecForTradingTermination,proto3" json:"oracle_spec_for_trading_termination,omitempty"`
	// The binding between the oracle spec and the settlement price
	OracleSpecBinding    *OracleSpecToFutureBinding `protobuf:"bytes,7,opt,name=oracle_spec_binding,json=oracleSpecBinding,proto3" json:"oracle_spec_binding,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *FutureProduct) Reset()         { *m = FutureProduct{} }
func (m *FutureProduct) String() string { return proto.CompactTextString(m) }
func (*FutureProduct) ProtoMessage()    {}
func (*FutureProduct) Descriptor() ([]byte, []int) {
	return fileDescriptor_c891e73c7d2524a3, []int{0}
}

func (m *FutureProduct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FutureProduct.Unmarshal(m, b)
}
func (m *FutureProduct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FutureProduct.Marshal(b, m, deterministic)
}
func (m *FutureProduct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FutureProduct.Merge(m, src)
}
func (m *FutureProduct) XXX_Size() int {
	return xxx_messageInfo_FutureProduct.Size(m)
}
func (m *FutureProduct) XXX_DiscardUnknown() {
	xxx_messageInfo_FutureProduct.DiscardUnknown(m)
}

var xxx_messageInfo_FutureProduct proto.InternalMessageInfo

func (m *FutureProduct) GetMaturity() string {
	if m != nil {
		return m.Maturity
	}
	return ""
}

func (m *FutureProduct) GetSettlementAsset() string {
	if m != nil {
		return m.SettlementAsset
	}
	return ""
}

func (m *FutureProduct) GetQuoteName() string {
	if m != nil {
		return m.QuoteName
	}
	return ""
}

func (m *FutureProduct) GetOracleSpecForSettlementPrice() *v1.OracleSpecConfiguration {
	if m != nil {
		return m.OracleSpecForSettlementPrice
	}
	return nil
}

func (m *FutureProduct) GetOracleSpecForTradingTermination() *v1.OracleSpecConfiguration {
	if m != nil {
		return m.OracleSpecForTradingTermination
	}
	return nil
}

func (m *FutureProduct) GetOracleSpecBinding() *OracleSpecToFutureBinding {
	if m != nil {
		return m.OracleSpecBinding
	}
	return nil
}

// Instrument configuration
type InstrumentConfiguration struct {
	// Instrument name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Instrument code
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// Product specification
	//
	// Types that are valid to be assigned to Product:
	//	*InstrumentConfiguration_Future
	Product              isInstrumentConfiguration_Product `protobuf_oneof:"product"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *InstrumentConfiguration) Reset()         { *m = InstrumentConfiguration{} }
func (m *InstrumentConfiguration) String() string { return proto.CompactTextString(m) }
func (*InstrumentConfiguration) ProtoMessage()    {}
func (*InstrumentConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_c891e73c7d2524a3, []int{1}
}

func (m *InstrumentConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstrumentConfiguration.Unmarshal(m, b)
}
func (m *InstrumentConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstrumentConfiguration.Marshal(b, m, deterministic)
}
func (m *InstrumentConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstrumentConfiguration.Merge(m, src)
}
func (m *InstrumentConfiguration) XXX_Size() int {
	return xxx_messageInfo_InstrumentConfiguration.Size(m)
}
func (m *InstrumentConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_InstrumentConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_InstrumentConfiguration proto.InternalMessageInfo

func (m *InstrumentConfiguration) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InstrumentConfiguration) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type isInstrumentConfiguration_Product interface {
	isInstrumentConfiguration_Product()
}

type InstrumentConfiguration_Future struct {
	Future *FutureProduct `protobuf:"bytes,100,opt,name=future,proto3,oneof"`
}

func (*InstrumentConfiguration_Future) isInstrumentConfiguration_Product() {}

func (m *InstrumentConfiguration) GetProduct() isInstrumentConfiguration_Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *InstrumentConfiguration) GetFuture() *FutureProduct {
	if x, ok := m.GetProduct().(*InstrumentConfiguration_Future); ok {
		return x.Future
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*InstrumentConfiguration) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*InstrumentConfiguration_Future)(nil),
	}
}

// Configuration for a new market on Vega
type NewMarketConfiguration struct {
	// New market instrument configuration
	Instrument *InstrumentConfiguration `protobuf:"bytes,1,opt,name=instrument,proto3" json:"instrument,omitempty"`
	// Decimal places used for the new market
	DecimalPlaces uint64 `protobuf:"varint,2,opt,name=decimal_places,json=decimalPlaces,proto3" json:"decimal_places,omitempty"`
	// Optional new market meta data, tags
	Metadata []string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty"`
	// Price monitoring parameters
	PriceMonitoringParameters *PriceMonitoringParameters `protobuf:"bytes,4,opt,name=price_monitoring_parameters,json=priceMonitoringParameters,proto3" json:"price_monitoring_parameters,omitempty"`
	// Liquidity monitoring parameters
	LiquidityMonitoringParameters *LiquidityMonitoringParameters `protobuf:"bytes,5,opt,name=liquidity_monitoring_parameters,json=liquidityMonitoringParameters,proto3" json:"liquidity_monitoring_parameters,omitempty"`
	// New market risk model parameters
	//
	// Types that are valid to be assigned to RiskParameters:
	//	*NewMarketConfiguration_Simple
	//	*NewMarketConfiguration_LogNormal
	RiskParameters isNewMarketConfiguration_RiskParameters `protobuf_oneof:"risk_parameters"`
	// Trading mode for the new market
	//
	// Types that are valid to be assigned to TradingMode:
	//	*NewMarketConfiguration_Continuous
	//	*NewMarketConfiguration_Discrete
	TradingMode          isNewMarketConfiguration_TradingMode `protobuf_oneof:"trading_mode"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *NewMarketConfiguration) Reset()         { *m = NewMarketConfiguration{} }
func (m *NewMarketConfiguration) String() string { return proto.CompactTextString(m) }
func (*NewMarketConfiguration) ProtoMessage()    {}
func (*NewMarketConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_c891e73c7d2524a3, []int{2}
}

func (m *NewMarketConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewMarketConfiguration.Unmarshal(m, b)
}
func (m *NewMarketConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewMarketConfiguration.Marshal(b, m, deterministic)
}
func (m *NewMarketConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewMarketConfiguration.Merge(m, src)
}
func (m *NewMarketConfiguration) XXX_Size() int {
	return xxx_messageInfo_NewMarketConfiguration.Size(m)
}
func (m *NewMarketConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_NewMarketConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_NewMarketConfiguration proto.InternalMessageInfo

func (m *NewMarketConfiguration) GetInstrument() *InstrumentConfiguration {
	if m != nil {
		return m.Instrument
	}
	return nil
}

func (m *NewMarketConfiguration) GetDecimalPlaces() uint64 {
	if m != nil {
		return m.DecimalPlaces
	}
	return 0
}

func (m *NewMarketConfiguration) GetMetadata() []string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *NewMarketConfiguration) GetPriceMonitoringParameters() *PriceMonitoringParameters {
	if m != nil {
		return m.PriceMonitoringParameters
	}
	return nil
}

func (m *NewMarketConfiguration) GetLiquidityMonitoringParameters() *LiquidityMonitoringParameters {
	if m != nil {
		return m.LiquidityMonitoringParameters
	}
	return nil
}

type isNewMarketConfiguration_RiskParameters interface {
	isNewMarketConfiguration_RiskParameters()
}

type NewMarketConfiguration_Simple struct {
	Simple *SimpleModelParams `protobuf:"bytes,100,opt,name=simple,proto3,oneof"`
}

type NewMarketConfiguration_LogNormal struct {
	LogNormal *LogNormalRiskModel `protobuf:"bytes,101,opt,name=log_normal,json=logNormal,proto3,oneof"`
}

func (*NewMarketConfiguration_Simple) isNewMarketConfiguration_RiskParameters() {}

func (*NewMarketConfiguration_LogNormal) isNewMarketConfiguration_RiskParameters() {}

func (m *NewMarketConfiguration) GetRiskParameters() isNewMarketConfiguration_RiskParameters {
	if m != nil {
		return m.RiskParameters
	}
	return nil
}

func (m *NewMarketConfiguration) GetSimple() *SimpleModelParams {
	if x, ok := m.GetRiskParameters().(*NewMarketConfiguration_Simple); ok {
		return x.Simple
	}
	return nil
}

func (m *NewMarketConfiguration) GetLogNormal() *LogNormalRiskModel {
	if x, ok := m.GetRiskParameters().(*NewMarketConfiguration_LogNormal); ok {
		return x.LogNormal
	}
	return nil
}

type isNewMarketConfiguration_TradingMode interface {
	isNewMarketConfiguration_TradingMode()
}

type NewMarketConfiguration_Continuous struct {
	Continuous *ContinuousTrading `protobuf:"bytes,200,opt,name=continuous,proto3,oneof"`
}

type NewMarketConfiguration_Discrete struct {
	Discrete *DiscreteTrading `protobuf:"bytes,201,opt,name=discrete,proto3,oneof"`
}

func (*NewMarketConfiguration_Continuous) isNewMarketConfiguration_TradingMode() {}

func (*NewMarketConfiguration_Discrete) isNewMarketConfiguration_TradingMode() {}

func (m *NewMarketConfiguration) GetTradingMode() isNewMarketConfiguration_TradingMode {
	if m != nil {
		return m.TradingMode
	}
	return nil
}

func (m *NewMarketConfiguration) GetContinuous() *ContinuousTrading {
	if x, ok := m.GetTradingMode().(*NewMarketConfiguration_Continuous); ok {
		return x.Continuous
	}
	return nil
}

func (m *NewMarketConfiguration) GetDiscrete() *DiscreteTrading {
	if x, ok := m.GetTradingMode().(*NewMarketConfiguration_Discrete); ok {
		return x.Discrete
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*NewMarketConfiguration) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*NewMarketConfiguration_Simple)(nil),
		(*NewMarketConfiguration_LogNormal)(nil),
		(*NewMarketConfiguration_Continuous)(nil),
		(*NewMarketConfiguration_Discrete)(nil),
	}
}

// A commitment of liquidity to be made by the party which proposes a market
type NewMarketCommitment struct {
	// Specified as a unitless number that represents the amount of settlement asset of the market
	CommitmentAmount uint64 `protobuf:"varint,1,opt,name=commitment_amount,json=commitmentAmount,proto3" json:"commitment_amount,omitempty"`
	// Nominated liquidity fee factor, which is an input to the calculation of taker fees on the market, as per seeting fees and rewarding liquidity providers
	Fee string `protobuf:"bytes,2,opt,name=fee,proto3" json:"fee,omitempty"`
	// A set of liquidity sell orders to meet the liquidity provision obligation
	Sells []*LiquidityOrder `protobuf:"bytes,3,rep,name=sells,proto3" json:"sells,omitempty"`
	// A set of liquidity buy orders to meet the liquidity provision obligation
	Buys []*LiquidityOrder `protobuf:"bytes,4,rep,name=buys,proto3" json:"buys,omitempty"`
	// A reference to be associated to all orders created from this commitment
	Reference            string   `protobuf:"bytes,5,opt,name=reference,proto3" json:"reference,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewMarketCommitment) Reset()         { *m = NewMarketCommitment{} }
func (m *NewMarketCommitment) String() string { return proto.CompactTextString(m) }
func (*NewMarketCommitment) ProtoMessage()    {}
func (*NewMarketCommitment) Descriptor() ([]byte, []int) {
	return fileDescriptor_c891e73c7d2524a3, []int{3}
}

func (m *NewMarketCommitment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewMarketCommitment.Unmarshal(m, b)
}
func (m *NewMarketCommitment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewMarketCommitment.Marshal(b, m, deterministic)
}
func (m *NewMarketCommitment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewMarketCommitment.Merge(m, src)
}
func (m *NewMarketCommitment) XXX_Size() int {
	return xxx_messageInfo_NewMarketCommitment.Size(m)
}
func (m *NewMarketCommitment) XXX_DiscardUnknown() {
	xxx_messageInfo_NewMarketCommitment.DiscardUnknown(m)
}

var xxx_messageInfo_NewMarketCommitment proto.InternalMessageInfo

func (m *NewMarketCommitment) GetCommitmentAmount() uint64 {
	if m != nil {
		return m.CommitmentAmount
	}
	return 0
}

func (m *NewMarketCommitment) GetFee() string {
	if m != nil {
		return m.Fee
	}
	return ""
}

func (m *NewMarketCommitment) GetSells() []*LiquidityOrder {
	if m != nil {
		return m.Sells
	}
	return nil
}

func (m *NewMarketCommitment) GetBuys() []*LiquidityOrder {
	if m != nil {
		return m.Buys
	}
	return nil
}

func (m *NewMarketCommitment) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

// New market on Vega
type NewMarket struct {
	// The configuration of the new market
	Changes *NewMarketConfiguration `protobuf:"bytes,1,opt,name=changes,proto3" json:"changes,omitempty"`
	// The commitment from the party creating the NewMarket proposal
	LiquidityCommitment  *NewMarketCommitment `protobuf:"bytes,2,opt,name=liquidity_commitment,json=liquidityCommitment,proto3" json:"liquidity_commitment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *NewMarket) Reset()         { *m = NewMarket{} }
func (m *NewMarket) String() string { return proto.CompactTextString(m) }
func (*NewMarket) ProtoMessage()    {}
func (*NewMarket) Descriptor() ([]byte, []int) {
	return fileDescriptor_c891e73c7d2524a3, []int{4}
}

func (m *NewMarket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewMarket.Unmarshal(m, b)
}
func (m *NewMarket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewMarket.Marshal(b, m, deterministic)
}
func (m *NewMarket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewMarket.Merge(m, src)
}
func (m *NewMarket) XXX_Size() int {
	return xxx_messageInfo_NewMarket.Size(m)
}
func (m *NewMarket) XXX_DiscardUnknown() {
	xxx_messageInfo_NewMarket.DiscardUnknown(m)
}

var xxx_messageInfo_NewMarket proto.InternalMessageInfo

func (m *NewMarket) GetChanges() *NewMarketConfiguration {
	if m != nil {
		return m.Changes
	}
	return nil
}

func (m *NewMarket) GetLiquidityCommitment() *NewMarketCommitment {
	if m != nil {
		return m.LiquidityCommitment
	}
	return nil
}

// Update an existing market on Vega
type UpdateMarket struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateMarket) Reset()         { *m = UpdateMarket{} }
func (m *UpdateMarket) String() string { return proto.CompactTextString(m) }
func (*UpdateMarket) ProtoMessage()    {}
func (*UpdateMarket) Descriptor() ([]byte, []int) {
	return fileDescriptor_c891e73c7d2524a3, []int{5}
}

func (m *UpdateMarket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMarket.Unmarshal(m, b)
}
func (m *UpdateMarket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMarket.Marshal(b, m, deterministic)
}
func (m *UpdateMarket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMarket.Merge(m, src)
}
func (m *UpdateMarket) XXX_Size() int {
	return xxx_messageInfo_UpdateMarket.Size(m)
}
func (m *UpdateMarket) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMarket.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMarket proto.InternalMessageInfo

// Update network configuration on Vega
type UpdateNetworkParameter struct {
	// The network parameter to update
	Changes              *NetworkParameter `protobuf:"bytes,1,opt,name=changes,proto3" json:"changes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UpdateNetworkParameter) Reset()         { *m = UpdateNetworkParameter{} }
func (m *UpdateNetworkParameter) String() string { return proto.CompactTextString(m) }
func (*UpdateNetworkParameter) ProtoMessage()    {}
func (*UpdateNetworkParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_c891e73c7d2524a3, []int{6}
}

func (m *UpdateNetworkParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNetworkParameter.Unmarshal(m, b)
}
func (m *UpdateNetworkParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNetworkParameter.Marshal(b, m, deterministic)
}
func (m *UpdateNetworkParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNetworkParameter.Merge(m, src)
}
func (m *UpdateNetworkParameter) XXX_Size() int {
	return xxx_messageInfo_UpdateNetworkParameter.Size(m)
}
func (m *UpdateNetworkParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNetworkParameter.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNetworkParameter proto.InternalMessageInfo

func (m *UpdateNetworkParameter) GetChanges() *NetworkParameter {
	if m != nil {
		return m.Changes
	}
	return nil
}

// New asset on Vega
type NewAsset struct {
	// The configuration of the new asset
	Changes              *AssetDetails `protobuf:"bytes,1,opt,name=changes,proto3" json:"changes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *NewAsset) Reset()         { *m = NewAsset{} }
func (m *NewAsset) String() string { return proto.CompactTextString(m) }
func (*NewAsset) ProtoMessage()    {}
func (*NewAsset) Descriptor() ([]byte, []int) {
	return fileDescriptor_c891e73c7d2524a3, []int{7}
}

func (m *NewAsset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewAsset.Unmarshal(m, b)
}
func (m *NewAsset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewAsset.Marshal(b, m, deterministic)
}
func (m *NewAsset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewAsset.Merge(m, src)
}
func (m *NewAsset) XXX_Size() int {
	return xxx_messageInfo_NewAsset.Size(m)
}
func (m *NewAsset) XXX_DiscardUnknown() {
	xxx_messageInfo_NewAsset.DiscardUnknown(m)
}

var xxx_messageInfo_NewAsset proto.InternalMessageInfo

func (m *NewAsset) GetChanges() *AssetDetails {
	if m != nil {
		return m.Changes
	}
	return nil
}

// Terms for a governance proposal on Vega
type ProposalTerms struct {
	// Timestamp (Unix time in seconds) when voting closes for this proposal,
	// constrained by `minCloseInSeconds` and `maxCloseInSeconds` network parameters
	ClosingTimestamp int64 `protobuf:"varint,1,opt,name=closing_timestamp,json=closingTimestamp,proto3" json:"closing_timestamp,omitempty"`
	// Timestamp (Unix time in seconds) when proposal gets enacted (if passed),
	// constrained by `minEnactInSeconds` and `maxEnactInSeconds` network parameters
	EnactmentTimestamp int64 `protobuf:"varint,2,opt,name=enactment_timestamp,json=enactmentTimestamp,proto3" json:"enactment_timestamp,omitempty"`
	// Validation timestamp (Unix time in seconds)
	ValidationTimestamp int64 `protobuf:"varint,3,opt,name=validation_timestamp,json=validationTimestamp,proto3" json:"validation_timestamp,omitempty"`
	// Changes being proposed
	//
	// Types that are valid to be assigned to Change:
	//	*ProposalTerms_UpdateMarket
	//	*ProposalTerms_NewMarket
	//	*ProposalTerms_UpdateNetworkParameter
	//	*ProposalTerms_NewAsset
	Change               isProposalTerms_Change `protobuf_oneof:"change"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ProposalTerms) Reset()         { *m = ProposalTerms{} }
func (m *ProposalTerms) String() string { return proto.CompactTextString(m) }
func (*ProposalTerms) ProtoMessage()    {}
func (*ProposalTerms) Descriptor() ([]byte, []int) {
	return fileDescriptor_c891e73c7d2524a3, []int{8}
}

func (m *ProposalTerms) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProposalTerms.Unmarshal(m, b)
}
func (m *ProposalTerms) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProposalTerms.Marshal(b, m, deterministic)
}
func (m *ProposalTerms) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProposalTerms.Merge(m, src)
}
func (m *ProposalTerms) XXX_Size() int {
	return xxx_messageInfo_ProposalTerms.Size(m)
}
func (m *ProposalTerms) XXX_DiscardUnknown() {
	xxx_messageInfo_ProposalTerms.DiscardUnknown(m)
}

var xxx_messageInfo_ProposalTerms proto.InternalMessageInfo

func (m *ProposalTerms) GetClosingTimestamp() int64 {
	if m != nil {
		return m.ClosingTimestamp
	}
	return 0
}

func (m *ProposalTerms) GetEnactmentTimestamp() int64 {
	if m != nil {
		return m.EnactmentTimestamp
	}
	return 0
}

func (m *ProposalTerms) GetValidationTimestamp() int64 {
	if m != nil {
		return m.ValidationTimestamp
	}
	return 0
}

type isProposalTerms_Change interface {
	isProposalTerms_Change()
}

type ProposalTerms_UpdateMarket struct {
	UpdateMarket *UpdateMarket `protobuf:"bytes,101,opt,name=update_market,json=updateMarket,proto3,oneof"`
}

type ProposalTerms_NewMarket struct {
	NewMarket *NewMarket `protobuf:"bytes,102,opt,name=new_market,json=newMarket,proto3,oneof"`
}

type ProposalTerms_UpdateNetworkParameter struct {
	UpdateNetworkParameter *UpdateNetworkParameter `protobuf:"bytes,103,opt,name=update_network_parameter,json=updateNetworkParameter,proto3,oneof"`
}

type ProposalTerms_NewAsset struct {
	NewAsset *NewAsset `protobuf:"bytes,104,opt,name=new_asset,json=newAsset,proto3,oneof"`
}

func (*ProposalTerms_UpdateMarket) isProposalTerms_Change() {}

func (*ProposalTerms_NewMarket) isProposalTerms_Change() {}

func (*ProposalTerms_UpdateNetworkParameter) isProposalTerms_Change() {}

func (*ProposalTerms_NewAsset) isProposalTerms_Change() {}

func (m *ProposalTerms) GetChange() isProposalTerms_Change {
	if m != nil {
		return m.Change
	}
	return nil
}

func (m *ProposalTerms) GetUpdateMarket() *UpdateMarket {
	if x, ok := m.GetChange().(*ProposalTerms_UpdateMarket); ok {
		return x.UpdateMarket
	}
	return nil
}

func (m *ProposalTerms) GetNewMarket() *NewMarket {
	if x, ok := m.GetChange().(*ProposalTerms_NewMarket); ok {
		return x.NewMarket
	}
	return nil
}

func (m *ProposalTerms) GetUpdateNetworkParameter() *UpdateNetworkParameter {
	if x, ok := m.GetChange().(*ProposalTerms_UpdateNetworkParameter); ok {
		return x.UpdateNetworkParameter
	}
	return nil
}

func (m *ProposalTerms) GetNewAsset() *NewAsset {
	if x, ok := m.GetChange().(*ProposalTerms_NewAsset); ok {
		return x.NewAsset
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ProposalTerms) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ProposalTerms_UpdateMarket)(nil),
		(*ProposalTerms_NewMarket)(nil),
		(*ProposalTerms_UpdateNetworkParameter)(nil),
		(*ProposalTerms_NewAsset)(nil),
	}
}

// Governance data
type GovernanceData struct {
	// The governance proposal
	Proposal *Proposal `protobuf:"bytes,1,opt,name=proposal,proto3" json:"proposal,omitempty"`
	// All "yes" votes in favour of the proposal above
	Yes []*Vote `protobuf:"bytes,2,rep,name=yes,proto3" json:"yes,omitempty"`
	// All "no" votes against the proposal above
	No []*Vote `protobuf:"bytes,3,rep,name=no,proto3" json:"no,omitempty"`
	// All latest YES votes by party (guaranteed to be unique),
	// where key (string) is the party ID (public key) and
	// value (Vote) is the vote cast by the given party
	YesParty map[string]*Vote `protobuf:"bytes,4,rep,name=yes_party,json=yesParty,proto3" json:"yes_party,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// All latest NO votes by party (guaranteed to be unique),
	// where key (string) is the party ID (public key) and
	// value (Vote) is the vote cast by the given party
	NoParty              map[string]*Vote `protobuf:"bytes,5,rep,name=no_party,json=noParty,proto3" json:"no_party,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GovernanceData) Reset()         { *m = GovernanceData{} }
func (m *GovernanceData) String() string { return proto.CompactTextString(m) }
func (*GovernanceData) ProtoMessage()    {}
func (*GovernanceData) Descriptor() ([]byte, []int) {
	return fileDescriptor_c891e73c7d2524a3, []int{9}
}

func (m *GovernanceData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GovernanceData.Unmarshal(m, b)
}
func (m *GovernanceData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GovernanceData.Marshal(b, m, deterministic)
}
func (m *GovernanceData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GovernanceData.Merge(m, src)
}
func (m *GovernanceData) XXX_Size() int {
	return xxx_messageInfo_GovernanceData.Size(m)
}
func (m *GovernanceData) XXX_DiscardUnknown() {
	xxx_messageInfo_GovernanceData.DiscardUnknown(m)
}

var xxx_messageInfo_GovernanceData proto.InternalMessageInfo

func (m *GovernanceData) GetProposal() *Proposal {
	if m != nil {
		return m.Proposal
	}
	return nil
}

func (m *GovernanceData) GetYes() []*Vote {
	if m != nil {
		return m.Yes
	}
	return nil
}

func (m *GovernanceData) GetNo() []*Vote {
	if m != nil {
		return m.No
	}
	return nil
}

func (m *GovernanceData) GetYesParty() map[string]*Vote {
	if m != nil {
		return m.YesParty
	}
	return nil
}

func (m *GovernanceData) GetNoParty() map[string]*Vote {
	if m != nil {
		return m.NoParty
	}
	return nil
}

// Governance proposal
type Proposal struct {
	// Unique proposal identifier
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Proposal reference
	Reference string `protobuf:"bytes,2,opt,name=reference,proto3" json:"reference,omitempty"`
	// Party identifier of the author (the party submitting the proposal)
	PartyId string `protobuf:"bytes,3,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	// Proposal state - See (Proposal.State)[#vega.Proposal.State] definition
	State Proposal_State `protobuf:"varint,4,opt,name=state,proto3,enum=wallet.vega.Proposal_State" json:"state,omitempty"`
	// Proposal timestamp for date and time (in nanoseconds) when proposal was submitted to the network
	Timestamp int64 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Proposal configuration and the actual change that is meant to be executed when proposal is enacted
	Terms *ProposalTerms `protobuf:"bytes,6,opt,name=terms,proto3" json:"terms,omitempty"`
	// A reason for the current state of the proposal, this may be set in case of REJECTED and FAILED statuses
	Reason ProposalError `protobuf:"varint,7,opt,name=reason,proto3,enum=wallet.vega.ProposalError" json:"reason,omitempty"`
	// The detailed error associated to the reason.
	ErrorDetails         string   `protobuf:"bytes,8,opt,name=error_details,json=errorDetails,proto3" json:"error_details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Proposal) Reset()         { *m = Proposal{} }
func (m *Proposal) String() string { return proto.CompactTextString(m) }
func (*Proposal) ProtoMessage()    {}
func (*Proposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_c891e73c7d2524a3, []int{10}
}

func (m *Proposal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proposal.Unmarshal(m, b)
}
func (m *Proposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proposal.Marshal(b, m, deterministic)
}
func (m *Proposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proposal.Merge(m, src)
}
func (m *Proposal) XXX_Size() int {
	return xxx_messageInfo_Proposal.Size(m)
}
func (m *Proposal) XXX_DiscardUnknown() {
	xxx_messageInfo_Proposal.DiscardUnknown(m)
}

var xxx_messageInfo_Proposal proto.InternalMessageInfo

func (m *Proposal) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Proposal) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

func (m *Proposal) GetPartyId() string {
	if m != nil {
		return m.PartyId
	}
	return ""
}

func (m *Proposal) GetState() Proposal_State {
	if m != nil {
		return m.State
	}
	return Proposal_STATE_UNSPECIFIED
}

func (m *Proposal) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Proposal) GetTerms() *ProposalTerms {
	if m != nil {
		return m.Terms
	}
	return nil
}

func (m *Proposal) GetReason() ProposalError {
	if m != nil {
		return m.Reason
	}
	return ProposalError_PROPOSAL_ERROR_UNSPECIFIED
}

func (m *Proposal) GetErrorDetails() string {
	if m != nil {
		return m.ErrorDetails
	}
	return ""
}

// Governance vote
type Vote struct {
	// Voter's party identifier
	PartyId string `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	// Actual vote
	Value Vote_Value `protobuf:"varint,2,opt,name=value,proto3,enum=wallet.vega.Vote_Value" json:"value,omitempty"`
	// Identifier of the proposal being voted on
	ProposalId string `protobuf:"bytes,3,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	// Vote timestamp for date and time (in nanoseconds) when vote was submitted to the network
	Timestamp int64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Total number of governance token for the party that casted the vote
	TotalGovernanceTokenBalance uint64 `protobuf:"varint,5,opt,name=total_governance_token_balance,json=totalGovernanceTokenBalance,proto3" json:"total_governance_token_balance,omitempty"`
	// The weight of this vote based on the total of governance token
	TotalGovernanceTokenWeight string   `protobuf:"bytes,6,opt,name=total_governance_token_weight,json=totalGovernanceTokenWeight,proto3" json:"total_governance_token_weight,omitempty"`
	XXX_NoUnkeyedLiteral       struct{} `json:"-"`
	XXX_unrecognized           []byte   `json:"-"`
	XXX_sizecache              int32    `json:"-"`
}

func (m *Vote) Reset()         { *m = Vote{} }
func (m *Vote) String() string { return proto.CompactTextString(m) }
func (*Vote) ProtoMessage()    {}
func (*Vote) Descriptor() ([]byte, []int) {
	return fileDescriptor_c891e73c7d2524a3, []int{11}
}

func (m *Vote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vote.Unmarshal(m, b)
}
func (m *Vote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vote.Marshal(b, m, deterministic)
}
func (m *Vote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vote.Merge(m, src)
}
func (m *Vote) XXX_Size() int {
	return xxx_messageInfo_Vote.Size(m)
}
func (m *Vote) XXX_DiscardUnknown() {
	xxx_messageInfo_Vote.DiscardUnknown(m)
}

var xxx_messageInfo_Vote proto.InternalMessageInfo

func (m *Vote) GetPartyId() string {
	if m != nil {
		return m.PartyId
	}
	return ""
}

func (m *Vote) GetValue() Vote_Value {
	if m != nil {
		return m.Value
	}
	return Vote_VALUE_UNSPECIFIED
}

func (m *Vote) GetProposalId() string {
	if m != nil {
		return m.ProposalId
	}
	return ""
}

func (m *Vote) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Vote) GetTotalGovernanceTokenBalance() uint64 {
	if m != nil {
		return m.TotalGovernanceTokenBalance
	}
	return 0
}

func (m *Vote) GetTotalGovernanceTokenWeight() string {
	if m != nil {
		return m.TotalGovernanceTokenWeight
	}
	return ""
}

func init() {
	proto.RegisterEnum("wallet.vega.ProposalError", ProposalError_name, ProposalError_value)
	proto.RegisterEnum("wallet.vega.Proposal_State", Proposal_State_name, Proposal_State_value)
	proto.RegisterEnum("wallet.vega.Vote_Value", Vote_Value_name, Vote_Value_value)
	proto.RegisterType((*FutureProduct)(nil), "wallet.vega.FutureProduct")
	proto.RegisterType((*InstrumentConfiguration)(nil), "wallet.vega.InstrumentConfiguration")
	proto.RegisterType((*NewMarketConfiguration)(nil), "wallet.vega.NewMarketConfiguration")
	proto.RegisterType((*NewMarketCommitment)(nil), "wallet.vega.NewMarketCommitment")
	proto.RegisterType((*NewMarket)(nil), "wallet.vega.NewMarket")
	proto.RegisterType((*UpdateMarket)(nil), "wallet.vega.UpdateMarket")
	proto.RegisterType((*UpdateNetworkParameter)(nil), "wallet.vega.UpdateNetworkParameter")
	proto.RegisterType((*NewAsset)(nil), "wallet.vega.NewAsset")
	proto.RegisterType((*ProposalTerms)(nil), "wallet.vega.ProposalTerms")
	proto.RegisterType((*GovernanceData)(nil), "wallet.vega.GovernanceData")
	proto.RegisterMapType((map[string]*Vote)(nil), "wallet.vega.GovernanceData.NoPartyEntry")
	proto.RegisterMapType((map[string]*Vote)(nil), "wallet.vega.GovernanceData.YesPartyEntry")
	proto.RegisterType((*Proposal)(nil), "wallet.vega.Proposal")
	proto.RegisterType((*Vote)(nil), "wallet.vega.Vote")
}

func init() { proto.RegisterFile("proto/governance.proto", fileDescriptor_c891e73c7d2524a3) }

var fileDescriptor_c891e73c7d2524a3 = []byte{
	// 2161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x58, 0xcd, 0x72, 0xdb, 0xc8,
	0x11, 0x16, 0x49, 0x51, 0x22, 0x5b, 0x3f, 0x0b, 0x8d, 0xd6, 0x32, 0x4d, 0xd9, 0x96, 0x4c, 0xaf,
	0x6d, 0xd9, 0x5e, 0x91, 0x2b, 0x79, 0xe3, 0x75, 0xad, 0x0f, 0x59, 0x90, 0x18, 0x59, 0x58, 0x93,
	0x00, 0x33, 0x00, 0xe5, 0x38, 0x17, 0x14, 0x4c, 0x8e, 0x68, 0x94, 0x40, 0x0c, 0x17, 0x00, 0xa5,
	0xd2, 0x21, 0xf7, 0x9c, 0x73, 0xc8, 0x2b, 0xe4, 0x94, 0x5c, 0xf3, 0x0a, 0x49, 0x55, 0xce, 0xb9,
	0xa5, 0xb6, 0x6a, 0xef, 0x79, 0x80, 0x1c, 0x52, 0x95, 0xc2, 0x00, 0x04, 0x08, 0x0a, 0x92, 0xf3,
	0x73, 0x32, 0xd1, 0xfd, 0xf5, 0xd7, 0x3d, 0xfd, 0x37, 0x63, 0xc1, 0xd6, 0xd8, 0x65, 0x3e, 0x6b,
	0x0c, 0xd9, 0x39, 0x75, 0x1d, 0xd3, 0xe9, 0xd3, 0x3a, 0x17, 0xa0, 0x95, 0x0b, 0xd3, 0xb6, 0xa9,
	0x5f, 0x3f, 0xa7, 0x43, 0xb3, 0xfa, 0x72, 0x68, 0xf9, 0x1f, 0x27, 0x1f, 0xea, 0x7d, 0x36, 0x6a,
	0x8c, 0x2e, 0x2c, 0xff, 0x8c, 0x5d, 0x34, 0x86, 0x6c, 0x9f, 0x23, 0xf7, 0xcf, 0x4d, 0xdb, 0x1a,
	0x98, 0x3e, 0x73, 0xbd, 0x46, 0xfc, 0x33, 0x24, 0xa9, 0x6e, 0x86, 0xe4, 0x23, 0xd3, 0x3d, 0xa3,
	0xbe, 0x17, 0x09, 0x85, 0x50, 0x18, 0x10, 0x47, 0x12, 0x14, 0x4a, 0x4c, 0xcf, 0x4b, 0x50, 0xdb,
	0xa1, 0x8c, 0xb9, 0x66, 0xdf, 0xa6, 0x5e, 0xe3, 0xfc, 0xa0, 0xe1, 0x8d, 0x69, 0x3f, 0x54, 0xd6,
	0xfe, 0x5e, 0x80, 0xb5, 0xa3, 0x89, 0x3f, 0x71, 0x69, 0xd7, 0x65, 0x83, 0x49, 0xdf, 0x47, 0x35,
	0x28, 0x8d, 0x4c, 0x7f, 0xe2, 0x5a, 0xfe, 0x65, 0x25, 0xb7, 0x9b, 0xdb, 0x2b, 0x37, 0x97, 0x7e,
	0xfa, 0x71, 0x27, 0xff, 0xcb, 0x1c, 0x89, 0xe5, 0xe8, 0x00, 0x04, 0x8f, 0xfa, 0xbe, 0x4d, 0x47,
	0xd4, 0xf1, 0x0d, 0xee, 0xad, 0x92, 0x4f, 0x61, 0x3f, 0x4b, 0xf4, 0x62, 0xa0, 0x46, 0x8f, 0x00,
	0x7e, 0x98, 0x30, 0x9f, 0x1a, 0x8e, 0x39, 0xa2, 0x95, 0x42, 0x0a, 0x5c, 0xe6, 0x1a, 0xc5, 0x1c,
	0x51, 0x74, 0x01, 0xbb, 0x61, 0xa0, 0x46, 0x10, 0xa4, 0x71, 0xca, 0x5c, 0x63, 0xc6, 0xd3, 0xd8,
	0xb5, 0xfa, 0xb4, 0x52, 0xdc, 0xcd, 0xed, 0xad, 0x1c, 0x36, 0xea, 0x33, 0x79, 0xad, 0x47, 0xa7,
	0xab, 0x9f, 0x1f, 0xd4, 0x55, 0xfe, 0x53, 0x1b, 0xd3, 0x7e, 0x8b, 0x39, 0xa7, 0xd6, 0x70, 0xe2,
	0x9a, 0xbe, 0xc5, 0x1c, 0x72, 0x97, 0xc5, 0x8a, 0x23, 0xe6, 0x6a, 0x31, 0x6b, 0x37, 0x20, 0x45,
	0xbf, 0x86, 0x87, 0xf3, 0x8e, 0x7d, 0xd7, 0x1c, 0x58, 0xce, 0xd0, 0xf0, 0xa9, 0x3b, 0xb2, 0x1c,
	0x4e, 0x52, 0x59, 0xfa, 0xdf, 0x7c, 0xef, 0xa4, 0x7c, 0xeb, 0x21, 0xb1, 0x9e, 0xf0, 0xa2, 0x13,
	0xd8, 0x9c, 0x75, 0xff, 0xc1, 0x72, 0x02, 0x44, 0x65, 0x99, 0xbb, 0x7b, 0x9c, 0x72, 0x97, 0xf8,
	0xd0, 0x59, 0x58, 0xba, 0x66, 0x88, 0x26, 0x1b, 0x89, 0x97, 0x48, 0x54, 0xfb, 0x6d, 0x0e, 0x6e,
	0xcb, 0x8e, 0xe7, 0xbb, 0x93, 0xe0, 0xa8, 0xa9, 0xa0, 0x50, 0x15, 0x16, 0x79, 0x31, 0xd2, 0x55,
	0xe6, 0xb2, 0x40, 0xd7, 0x67, 0x03, 0x3a, 0x57, 0x55, 0x2e, 0x43, 0x5f, 0xc3, 0xd2, 0x29, 0xf7,
	0x5b, 0x19, 0xf0, 0xf0, 0xaa, 0xa9, 0xf0, 0x52, 0xdd, 0x74, 0xbc, 0x40, 0x22, 0x6c, 0xb3, 0x0c,
	0xcb, 0xe3, 0x50, 0x58, 0xfb, 0x43, 0x11, 0xb6, 0x14, 0x7a, 0xd1, 0xe1, 0xcd, 0x9c, 0x8e, 0xa9,
	0x0d, 0x60, 0xc5, 0xe1, 0xf2, 0xc8, 0x56, 0x0e, 0xbf, 0x48, 0xf1, 0x5f, 0x73, 0x9a, 0x30, 0xc6,
	0xdd, 0x1c, 0x99, 0xb1, 0x47, 0x75, 0x58, 0x1f, 0xd0, 0xbe, 0x35, 0x32, 0x6d, 0x63, 0x6c, 0x9b,
	0x7d, 0xea, 0xf1, 0xf3, 0x2c, 0x36, 0x97, 0x7f, 0xfa, 0x71, 0xa7, 0x50, 0xf9, 0x5d, 0x8e, 0xac,
	0x45, 0xea, 0x2e, 0xd7, 0xa2, 0x2a, 0x94, 0x46, 0xd4, 0x37, 0x07, 0xa6, 0x6f, 0x56, 0x0a, 0xbb,
	0x85, 0xbd, 0x32, 0x89, 0xbf, 0xd1, 0x29, 0x6c, 0xf3, 0xf6, 0x33, 0x46, 0xcc, 0xb1, 0x7c, 0xe6,
	0x06, 0x9d, 0x31, 0x36, 0x5d, 0x73, 0x44, 0x7d, 0xea, 0x7a, 0x95, 0xc5, 0x8c, 0x4a, 0xf1, 0xce,
	0xea, 0xc4, 0xf0, 0x6e, 0x8c, 0x26, 0x77, 0xc6, 0xd7, 0xa9, 0x90, 0x0b, 0x3b, 0xb6, 0xf5, 0xc3,
	0xc4, 0x1a, 0x58, 0xfe, 0xe5, 0x35, 0xbe, 0xc2, 0x01, 0x78, 0x96, 0xf2, 0xd5, 0x9e, 0xda, 0x64,
	0xfa, 0xbb, 0x67, 0xdf, 0xa4, 0x46, 0xaf, 0x60, 0xc9, 0xb3, 0x46, 0x63, 0x7b, 0x5a, 0xd1, 0xfb,
	0x29, 0x6a, 0x8d, 0xab, 0x3a, 0x6c, 0x40, 0x6d, 0x6e, 0xe3, 0x05, 0x55, 0x0d, 0xf1, 0xe8, 0x3b,
	0x00, 0x9b, 0x0d, 0x0d, 0x87, 0xb9, 0x23, 0xd3, 0xae, 0x50, 0x6e, 0xbd, 0x93, 0x0e, 0x8c, 0x0d,
	0x15, 0xae, 0x25, 0x96, 0x77, 0xc6, 0x49, 0x8e, 0x17, 0x48, 0xd9, 0x9e, 0x4a, 0x91, 0x08, 0xd0,
	0x67, 0x8e, 0x6f, 0x39, 0x13, 0x36, 0xf1, 0x2a, 0x7f, 0xce, 0x65, 0x04, 0xd0, 0x8a, 0xf5, 0xd1,
	0xe4, 0x1c, 0xe7, 0xc8, 0x8c, 0x11, 0x7a, 0x0d, 0xa5, 0x81, 0xe5, 0xf5, 0x5d, 0xea, 0xd3, 0xca,
	0x5f, 0x42, 0x82, 0xbb, 0x29, 0x02, 0x29, 0xd2, 0x26, 0xe6, 0xb1, 0x41, 0x73, 0x03, 0x3e, 0x73,
	0x2d, 0xef, 0x6c, 0x26, 0xbf, 0xcd, 0x75, 0x58, 0x9d, 0xce, 0xfe, 0x88, 0x0d, 0x68, 0xed, 0x6f,
	0x39, 0xd8, 0x9c, 0xe9, 0xd7, 0xd1, 0xc8, 0xf2, 0x79, 0x7b, 0x3d, 0x87, 0x8d, 0x7e, 0xfc, 0x65,
	0x98, 0x23, 0x36, 0x89, 0x7a, 0x76, 0x91, 0x08, 0x89, 0x42, 0xe4, 0x72, 0x24, 0x40, 0xe1, 0x94,
	0x46, 0x03, 0x45, 0x82, 0x9f, 0xe8, 0x00, 0x8a, 0x1e, 0xb5, 0x6d, 0x8f, 0xb7, 0xda, 0xca, 0xe1,
	0x76, 0x76, 0x3d, 0x55, 0x77, 0x40, 0x5d, 0x12, 0x22, 0x51, 0x03, 0x16, 0x3f, 0x4c, 0x2e, 0x83,
	0x6e, 0xfb, 0xa4, 0x05, 0x07, 0xa2, 0xbb, 0x50, 0x76, 0xe9, 0x29, 0x75, 0xa9, 0x13, 0x2d, 0xce,
	0x32, 0x49, 0x04, 0xb5, 0xdf, 0xe7, 0xa0, 0x1c, 0x1f, 0x0c, 0x61, 0x58, 0xee, 0x7f, 0x34, 0x9d,
	0x21, 0xf5, 0xa2, 0xc1, 0x7b, 0x98, 0xe2, 0xcf, 0x9e, 0xd8, 0x78, 0xee, 0xa6, 0xb6, 0x48, 0x83,
	0xcf, 0x93, 0x06, 0x4e, 0xd2, 0xc0, 0x4f, 0xbe, 0x72, 0xb8, 0x7b, 0x1d, 0xe7, 0x14, 0x47, 0x36,
	0x63, 0xeb, 0x44, 0x58, 0x5b, 0x87, 0xd5, 0xde, 0x78, 0x60, 0xfa, 0x34, 0x84, 0xd7, 0xde, 0xc3,
	0x56, 0xf8, 0xad, 0x50, 0xff, 0x82, 0xb9, 0x67, 0x71, 0x33, 0xa3, 0x9f, 0xcf, 0x9f, 0xe2, 0xde,
	0x9c, 0xc7, 0x34, 0xfe, 0x4a, 0xfc, 0xb5, 0x37, 0x50, 0x52, 0xe8, 0x45, 0x78, 0x6b, 0xbd, 0x9e,
	0x27, 0xbb, 0x93, 0x22, 0xe3, 0x20, 0x89, 0xfa, 0xa6, 0x65, 0x7b, 0x57, 0x89, 0xfe, 0x5a, 0x80,
	0xb5, 0xae, 0xcb, 0xc6, 0xcc, 0x33, 0xed, 0x60, 0xd7, 0x7b, 0xe8, 0x05, 0x6c, 0xf4, 0x6d, 0xe6,
	0xf1, 0x4b, 0xc5, 0x1a, 0x51, 0xcf, 0x37, 0x47, 0x63, 0x4e, 0x5c, 0x08, 0xad, 0x85, 0x05, 0x22,
	0x44, 0x00, 0x7d, 0xaa, 0x47, 0xdf, 0xc0, 0x26, 0x75, 0xcc, 0x7e, 0xd8, 0x64, 0x89, 0x59, 0x3e,
	0x65, 0x86, 0x62, 0x48, 0x62, 0x78, 0x00, 0x9f, 0x47, 0xcf, 0x08, 0x8b, 0x39, 0x33, 0x96, 0xc1,
	0xe5, 0x5b, 0x20, 0x9b, 0x89, 0x2e, 0x31, 0xf9, 0x0e, 0xd6, 0x26, 0x3c, 0xad, 0x46, 0xf8, 0xd2,
	0x88, 0x26, 0x3a, 0x7d, 0xea, 0xd9, 0x42, 0x1c, 0x2f, 0x90, 0xd5, 0xc9, 0xcc, 0x37, 0xfa, 0x06,
	0xc0, 0xa1, 0x17, 0x53, 0xf3, 0x53, 0x6e, 0xbe, 0x95, 0x5d, 0xf3, 0x60, 0x0f, 0x38, 0x71, 0xf7,
	0x19, 0x50, 0x89, 0x5c, 0x3b, 0x61, 0x89, 0x92, 0x89, 0xac, 0x0c, 0x33, 0xda, 0x31, 0xbb, 0xfc,
	0xc7, 0x0b, 0x64, 0x6b, 0x92, 0xdd, 0x18, 0x5f, 0x43, 0xe0, 0x2d, 0x7a, 0xad, 0x7c, 0xe4, 0x8c,
	0xb7, 0xe6, 0x03, 0xe3, 0x05, 0x3d, 0x5e, 0x20, 0x25, 0x27, 0xfa, 0xdd, 0x2c, 0xc1, 0x52, 0x58,
	0xcf, 0xda, 0x9f, 0x0a, 0xb0, 0xfe, 0x26, 0x7e, 0xdc, 0x49, 0xc1, 0x9d, 0x70, 0x00, 0xa5, 0x71,
	0x54, 0xe0, 0xa8, 0x3f, 0x6e, 0xcd, 0x5d, 0x00, 0xa1, 0x92, 0xc4, 0x30, 0xf4, 0x10, 0x0a, 0x97,
	0xfc, 0x1e, 0x0a, 0x06, 0x78, 0x23, 0x85, 0x3e, 0x61, 0x3e, 0x25, 0x81, 0x16, 0x3d, 0x80, 0xbc,
	0xc3, 0xa2, 0xb5, 0x90, 0x81, 0xc9, 0x3b, 0x0c, 0x1d, 0x41, 0xf9, 0x92, 0x7a, 0x41, 0x8e, 0xfc,
	0xcb, 0x68, 0x1d, 0x3c, 0x4d, 0x21, 0xd3, 0xa1, 0xd6, 0xdf, 0x53, 0xaf, 0x1b, 0x60, 0xb1, 0xe3,
	0xbb, 0x97, 0xa4, 0x74, 0x19, 0x7d, 0xa2, 0x16, 0x94, 0x1c, 0x16, 0xd1, 0x14, 0x39, 0xcd, 0xde,
	0x4d, 0x34, 0x0a, 0x9b, 0x61, 0x59, 0x76, 0xc2, 0xaf, 0xaa, 0x02, 0x6b, 0x29, 0xfe, 0x60, 0xd9,
	0x9d, 0xd1, 0xe8, 0xfd, 0x48, 0x82, 0x9f, 0xe8, 0x09, 0x14, 0xcf, 0x4d, 0x7b, 0x42, 0xa3, 0x35,
	0x90, 0x71, 0xaa, 0x50, 0xff, 0x6d, 0xfe, 0x55, 0xae, 0xda, 0x81, 0xd5, 0x59, 0x47, 0xff, 0x27,
	0x5d, 0xed, 0x9f, 0x05, 0x28, 0x4d, 0x4b, 0x81, 0xd6, 0x21, 0x6f, 0x0d, 0x22, 0xaa, 0xbc, 0x35,
	0x48, 0x6f, 0xc8, 0xfc, 0xdc, 0x86, 0x44, 0x0f, 0xa0, 0xc4, 0x73, 0x63, 0x58, 0x83, 0xb9, 0x47,
	0xeb, 0x32, 0x97, 0xcb, 0x03, 0xf4, 0x2d, 0x14, 0x3d, 0xdf, 0xf4, 0x29, 0x7f, 0x02, 0xac, 0xcf,
	0x2d, 0xe5, 0xa9, 0xdb, 0xba, 0x16, 0x40, 0xc2, 0x87, 0xc7, 0x6f, 0x72, 0x39, 0x12, 0x9a, 0x04,
	0xce, 0x93, 0xb9, 0x2c, 0xf2, 0xb9, 0x4c, 0x04, 0xe8, 0x15, 0x14, 0x83, 0xb7, 0xa7, 0x17, 0xbd,
	0x3a, 0xab, 0x99, 0xcc, 0x7c, 0xb3, 0xc4, 0xcb, 0x27, 0x34, 0x40, 0x87, 0xb0, 0xe4, 0x52, 0xd3,
	0x63, 0x0e, 0x7f, 0x41, 0xae, 0x5f, 0x63, 0x8a, 0x5d, 0x97, 0xb9, 0x24, 0x42, 0xa2, 0x87, 0xb0,
	0x46, 0x03, 0x81, 0x31, 0x08, 0x17, 0x5a, 0xa5, 0xc4, 0x93, 0xb1, 0xca, 0x85, 0xd1, 0x92, 0xab,
	0xfd, 0x31, 0x07, 0x45, 0x7e, 0x14, 0x74, 0x0b, 0x36, 0x34, 0x5d, 0xd4, 0xb1, 0xd1, 0x53, 0xb4,
	0x2e, 0x6e, 0xc9, 0x47, 0x32, 0x96, 0x84, 0x05, 0x24, 0xc0, 0x6a, 0x28, 0x3e, 0x12, 0xe5, 0x36,
	0x96, 0x84, 0x1c, 0x5a, 0x07, 0x08, 0x25, 0x6a, 0x17, 0x2b, 0x42, 0x3e, 0x41, 0x74, 0x45, 0x4d,
	0xc3, 0x92, 0x50, 0x40, 0x08, 0xd6, 0x43, 0x09, 0xc1, 0xdf, 0xe3, 0x96, 0x8e, 0x25, 0x61, 0x31,
	0x91, 0x49, 0xb8, 0xd5, 0x96, 0x15, 0x2c, 0x09, 0x45, 0xb4, 0x01, 0x6b, 0xa1, 0x0c, 0x2b, 0x22,
	0x87, 0x2d, 0xa1, 0x1d, 0xd8, 0x0e, 0x45, 0xef, 0x44, 0x59, 0x97, 0x95, 0x37, 0xc6, 0x91, 0x4a,
	0x0c, 0x45, 0x95, 0xb0, 0x71, 0xa2, 0xea, 0x58, 0x58, 0xae, 0xfd, 0x23, 0x0f, 0x8b, 0x41, 0x3f,
	0xa4, 0x2a, 0x99, 0xcb, 0xae, 0xe4, 0xcb, 0xd9, 0xa6, 0x5a, 0x3f, 0xbc, 0x7d, 0xa5, 0xa9, 0xea,
	0x27, 0x81, 0x7a, 0xa6, 0x8a, 0x1c, 0x8e, 0x9e, 0xc0, 0xca, 0x74, 0xbe, 0xaf, 0xf6, 0x09, 0x4c,
	0x55, 0xf2, 0x20, 0x5d, 0xee, 0xc5, 0xf9, 0x72, 0xb7, 0xe0, 0xbe, 0xcf, 0x7c, 0xd3, 0x36, 0x92,
	0xff, 0x42, 0x1a, 0x3e, 0x3b, 0xa3, 0x8e, 0xf1, 0xc1, 0xb4, 0xcd, 0xe9, 0x05, 0xbe, 0x48, 0xb6,
	0x39, 0x2a, 0x19, 0x4c, 0x3d, 0xc0, 0x34, 0x43, 0x08, 0x12, 0xe1, 0xde, 0x35, 0x24, 0x17, 0xd4,
	0x1a, 0x7e, 0xf4, 0x79, 0x2f, 0x95, 0x49, 0x35, 0x8b, 0xe3, 0x1d, 0x47, 0xd4, 0x5e, 0x43, 0x91,
	0x9f, 0x33, 0x28, 0xf1, 0x89, 0xd8, 0xee, 0xcd, 0x97, 0x78, 0x15, 0x4a, 0xa1, 0x58, 0x51, 0x85,
	0x1c, 0x5a, 0x83, 0x72, 0xf8, 0xf5, 0x1e, 0x6b, 0x42, 0xfe, 0xd9, 0xbf, 0x56, 0x92, 0x4b, 0x8f,
	0xf7, 0x17, 0xba, 0x0f, 0xd5, 0x2e, 0x51, 0xbb, 0xaa, 0x26, 0xb6, 0x0d, 0x4c, 0x88, 0x4a, 0xe6,
	0xe8, 0x1e, 0x43, 0x6d, 0x4e, 0xdf, 0x6a, 0xab, 0x1a, 0x36, 0x74, 0xb9, 0x83, 0x0d, 0x5d, 0x55,
	0x0d, 0x4d, 0x55, 0x15, 0x21, 0xf7, 0x69, 0x5c, 0x5b, 0xd4, 0xb1, 0x90, 0xcf, 0xc0, 0xf1, 0x76,
	0x99, 0xe3, 0x2b, 0x7c, 0x1a, 0xc7, 0xf9, 0x16, 0x33, 0x70, 0xb2, 0xa2, 0xf5, 0x8e, 0x8e, 0xe4,
	0x96, 0x8c, 0x15, 0xdd, 0xd0, 0xd5, 0xb7, 0x58, 0xd1, 0x84, 0x22, 0xaa, 0xc3, 0xb3, 0x2b, 0xb8,
	0x13, 0xb1, 0x2d, 0x4b, 0x01, 0x5e, 0x27, 0xbd, 0x4e, 0x80, 0xd6, 0x70, 0xab, 0x47, 0x64, 0xfd,
	0xbd, 0xb0, 0x84, 0xee, 0xc1, 0x9d, 0x39, 0xbc, 0xa2, 0x1a, 0x5d, 0xa2, 0x4a, 0xbd, 0x96, 0x2e,
	0x2c, 0x67, 0xb8, 0xed, 0x29, 0x5a, 0xaf, 0xdb, 0x55, 0x89, 0x8e, 0xa5, 0x18, 0x57, 0x42, 0x2f,
	0xa0, 0x71, 0x8d, 0xdb, 0xa3, 0x9e, 0xde, 0x23, 0x78, 0x0a, 0xe5, 0xe7, 0xd2, 0x74, 0xb1, 0xd3,
	0x15, 0xca, 0x68, 0x1f, 0x9e, 0xce, 0x19, 0x4d, 0x51, 0x1d, 0x51, 0xe7, 0x01, 0x1a, 0xb2, 0x36,
	0x1d, 0x50, 0x40, 0x35, 0xb8, 0x7f, 0x35, 0x54, 0x9d, 0x88, 0x52, 0x30, 0x71, 0x1d, 0x55, 0xc2,
	0xc2, 0x0a, 0x7a, 0x0e, 0x4f, 0x6e, 0x88, 0x37, 0x05, 0x5e, 0x45, 0x4f, 0xe1, 0xd1, 0x15, 0xc2,
	0x60, 0x66, 0x83, 0xb8, 0x45, 0x5d, 0x56, 0x95, 0xe9, 0xfa, 0x58, 0xcb, 0x48, 0x6b, 0x47, 0xd6,
	0xb4, 0x80, 0xab, 0xd9, 0x93, 0xdb, 0xba, 0xac, 0x18, 0x41, 0x94, 0xba, 0x71, 0x24, 0xe3, 0xb6,
	0x24, 0xac, 0xa3, 0x03, 0xd8, 0xbf, 0x06, 0x8f, 0x49, 0xeb, 0xf0, 0x2b, 0xa3, 0xa5, 0x2a, 0x3a,
	0x09, 0xea, 0x2c, 0x4a, 0x12, 0xc1, 0x9a, 0x26, 0x7c, 0x86, 0x76, 0xe1, 0xee, 0x35, 0x29, 0xe4,
	0xd4, 0x82, 0x80, 0x9e, 0xc1, 0xe3, 0x2b, 0x88, 0x96, 0xda, 0xe9, 0x8a, 0xba, 0xdc, 0x6c, 0xe3,
	0x24, 0xb5, 0x9a, 0xb0, 0x81, 0x1e, 0xc1, 0x83, 0xab, 0xc9, 0x22, 0xb2, 0xf6, 0xd6, 0xe8, 0x8a,
	0x44, 0xec, 0x60, 0x1d, 0x13, 0x4d, 0x40, 0xe8, 0x2b, 0xf8, 0x72, 0x1e, 0x86, 0xf5, 0x77, 0x2a,
	0x99, 0x81, 0xc5, 0x61, 0xbc, 0xc5, 0xef, 0x85, 0x4d, 0x74, 0x08, 0xf5, 0xff, 0xd8, 0x82, 0x8f,
	0xa4, 0xf0, 0x39, 0x7a, 0x09, 0x87, 0x9f, 0xb4, 0xb9, 0x9a, 0xf5, 0x5b, 0xe8, 0x67, 0x70, 0x30,
	0x67, 0x17, 0x6c, 0xef, 0x20, 0x8b, 0x62, 0xaf, 0xc5, 0xa1, 0x52, 0x8f, 0x84, 0x36, 0x7c, 0xa4,
	0x3a, 0x62, 0xbb, 0x2d, 0x6c, 0xfd, 0xb7, 0x66, 0x6d, 0x91, 0xbc, 0xc1, 0xc2, 0xed, 0x8c, 0x28,
	0x3b, 0x22, 0x79, 0x8b, 0xf5, 0xb8, 0x74, 0x6d, 0xf9, 0x17, 0x3d, 0x59, 0x0a, 0xda, 0xb2, 0xa5,
	0x76, 0x3a, 0xb2, 0x1e, 0xcc, 0x92, 0x50, 0x41, 0x0d, 0x78, 0x3e, 0xbf, 0x12, 0xd4, 0x5e, 0x5b,
	0x32, 0x14, 0x55, 0xe7, 0x43, 0x27, 0x2a, 0xba, 0x1c, 0x5c, 0x0e, 0x21, 0x9b, 0x70, 0x27, 0xa3,
	0xef, 0xb2, 0x87, 0x45, 0xa8, 0xa2, 0x2f, 0x61, 0xef, 0x9a, 0x3e, 0x4a, 0x42, 0x30, 0xc4, 0x8e,
	0xda, 0x53, 0x74, 0x61, 0x3b, 0xa3, 0xe8, 0x31, 0x31, 0xc6, 0x53, 0xd8, 0xdd, 0x1b, 0x3a, 0x4d,
	0x3b, 0x16, 0xbb, 0x58, 0xb8, 0x77, 0x43, 0x84, 0xe9, 0x16, 0x12, 0xee, 0x67, 0x75, 0xba, 0xf8,
	0xbd, 0xca, 0x87, 0x57, 0x3f, 0x26, 0x58, 0x3b, 0x56, 0xa3, 0x54, 0x10, 0x2c, 0xb6, 0x8e, 0xb1,
	0x24, 0xec, 0x64, 0x24, 0xba, 0x2b, 0x12, 0x5d, 0x6e, 0xc9, 0xdd, 0xa8, 0x28, 0x99, 0x76, 0xbb,
	0x68, 0x0f, 0xbe, 0xb8, 0x69, 0x42, 0x0c, 0x09, 0xeb, 0xa2, 0xdc, 0xd6, 0x84, 0x07, 0xcd, 0xc6,
	0xaf, 0xf6, 0xfb, 0x6c, 0x40, 0xf9, 0x9d, 0xc9, 0xff, 0xc4, 0xd8, 0x67, 0x76, 0xdd, 0x62, 0x8d,
	0x21, 0xdb, 0x0f, 0x6f, 0xd3, 0x86, 0xe5, 0xf8, 0xc1, 0xa5, 0x63, 0x37, 0xb8, 0xfa, 0xc3, 0x12,
	0xff, 0xe7, 0xc5, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x42, 0x6d, 0x6f, 0x2d, 0x3f, 0x15, 0x00,
	0x00,
}
