[run]
allow-parallel-runners = true
print-linter-name = true

[linters]
enable-all = true
disable = [
    # To be fixed
    "bodyclose",
    "cyclop",
    "dupl",
    "exhaustivestruct",
    "funlen",
    "gochecknoglobals",
    "gochecknoinits",
    "gocognit",
    "goconst",
    "nestif",
    "paralleltest",
    "revive",
    "tagliatelle",
    "wrapcheck",
    "wsl",
    # Deprecated linters
    "golint",
    "interfacer",
    "maligned",
    "scopelint",
    # Won't be fixed
    # gci doesn't match our code style.
    "gci",
    # lll doesn't match our code style.
    "lll",
    # nlreturn doesn't match our code style.
    "nlreturn",
]

[issues.exclude-rules]
linters = ["staticcheck"]
text = "SA1019:"


