[run]
allow-parallel-runners = true
print-linter-name = true

[linters]
enable-all = true
disable = [
    # To be fixed
    "bodyclose",
    "cyclop",
    "dupl",
    "exhaustivestruct",
    "funlen",
    "gochecknoglobals",
    "gochecknoinits",
    "gocognit",
    "goconst",
    "gocritic",
    "goimports",
    "gomnd",
    "ifshort",
    "lll",
    "misspell",
    "nestif",
    "nlreturn",
    "noctx",
    "paralleltest",
    "prealloc",
    "revive",
    "stylecheck",
    "tagliatelle",
    "thelper",
    "whitespace",
    "wrapcheck",
    "wsl",
    # Deprecated linters
    "golint",
    "interfacer",
    "maligned",
    "scopelint",
    # Won't be fixed
    # gci doesn't match our code style.
    "gci"
]

[issues]
[[issues.exclude-rules]]
linters = ["staticcheck"]
text = "SA1019:"


