[run]
allow-parallel-runners = true
print-linter-name = true

[linters]
enable-all = true
disable = [
    # To be investigate
    "containedctx",
    "contextcheck",
    "cyclop",
    "dupl",
    "errchkjson",
    "exhaustivestruct",
    "funlen",
    "gocognit",
    "ifshort",
    "ireturn",
    "maintidx",
    "nestif",
    "nilnil",
    "nolintlint",
    "paralleltest",
    "predeclared",
    "revive",
    "tagliatelle",
    "varnamelen",
    "wrapcheck",
    "wsl",
    # Deprecated linters
    "golint",
    "interfacer",
    "maligned",
    "scopelint",
    # Won't be fixed
    # gci doesn't match our code style.
    "gci",
    # lll doesn't match our code style.
    "lll",
    # nlreturn doesn't match our code style.
    "nlreturn",
    # Sometimes we can't just have a const variable, and we need to make it a
    # variable instead.
    "gochecknoglobals",
]

[issues.exclude-rules]
linters = ["staticcheck"]
text = "SA1019:"


