Name = "fairground"
Level = "info"
TokenExpiry = "168h0m0s"
Port = 1789
Host = "127.0.0.1"

[API.GRPC]
Retries = 5
Hosts = [
    "n06.testnet.vega.xyz:3007",
    "n07.testnet.vega.xyz:3007",
    "n08.testnet.vega.xyz:3007",
    "n09.testnet.vega.xyz:3007",
    "n10.testnet.vega.xyz:3007",
    "n11.testnet.vega.xyz:3007",
    "n12.testnet.vega.xyz:3007",
    "n13.testnet.vega.xyz:3007",
    "n14.testnet.vega.xyz:3007",
    "n15.testnet.vega.xyz:3007",
    "n16.testnet.vega.xyz:3007",
    "n17.testnet.vega.xyz:3007",
    "n18.testnet.vega.xyz:3007",
    "n19.testnet.vega.xyz:3007",
    "n20.testnet.vega.xyz:3007"
]

[API.REST]
Hosts = [
    "https://lb.testnet.vega.xyz/datanode/rest"
]

[API.GraphQL]
Hosts = [
    "https://lb.testnet.vega.xyz/datanode/gql/query"
]

[Console]
URL = "console.fairground.wtf"
LocalPort = 1847
