// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/wallet/v1/wallet.proto

package v1

import (
	v1 "code.vegaprotocol.io/go-wallet/internal/proto/commands/v1"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SubmitTransactionRequest struct {
	PubKey    string `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	Propagate bool   `protobuf:"varint,2,opt,name=propagate,proto3" json:"propagate,omitempty"`
	// Types that are valid to be assigned to Command:
	//	*SubmitTransactionRequest_OrderSubmission
	//	*SubmitTransactionRequest_OrderCancellation
	//	*SubmitTransactionRequest_OrderAmendment
	//	*SubmitTransactionRequest_WithdrawSubmission
	//	*SubmitTransactionRequest_ProposalSubmission
	//	*SubmitTransactionRequest_VoteSubmission
	//	*SubmitTransactionRequest_LiquidityProvisionSubmission
	//	*SubmitTransactionRequest_DelegateSubmission
	//	*SubmitTransactionRequest_UndelegateAtEpochEndSubmission
	//	*SubmitTransactionRequest_NodeRegistration
	//	*SubmitTransactionRequest_NodeVote
	//	*SubmitTransactionRequest_NodeSignature
	//	*SubmitTransactionRequest_ChainEvent
	//	*SubmitTransactionRequest_OracleDataSubmission
	Command              isSubmitTransactionRequest_Command `protobuf_oneof:"command"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *SubmitTransactionRequest) Reset()         { *m = SubmitTransactionRequest{} }
func (m *SubmitTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*SubmitTransactionRequest) ProtoMessage()    {}
func (*SubmitTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7164113feb7df849, []int{0}
}

func (m *SubmitTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitTransactionRequest.Unmarshal(m, b)
}
func (m *SubmitTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitTransactionRequest.Marshal(b, m, deterministic)
}
func (m *SubmitTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitTransactionRequest.Merge(m, src)
}
func (m *SubmitTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_SubmitTransactionRequest.Size(m)
}
func (m *SubmitTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitTransactionRequest proto.InternalMessageInfo

func (m *SubmitTransactionRequest) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

func (m *SubmitTransactionRequest) GetPropagate() bool {
	if m != nil {
		return m.Propagate
	}
	return false
}

type isSubmitTransactionRequest_Command interface {
	isSubmitTransactionRequest_Command()
}

type SubmitTransactionRequest_OrderSubmission struct {
	OrderSubmission *v1.OrderSubmission `protobuf:"bytes,1001,opt,name=order_submission,json=orderSubmission,proto3,oneof"`
}

type SubmitTransactionRequest_OrderCancellation struct {
	OrderCancellation *v1.OrderCancellation `protobuf:"bytes,1002,opt,name=order_cancellation,json=orderCancellation,proto3,oneof"`
}

type SubmitTransactionRequest_OrderAmendment struct {
	OrderAmendment *v1.OrderAmendment `protobuf:"bytes,1003,opt,name=order_amendment,json=orderAmendment,proto3,oneof"`
}

type SubmitTransactionRequest_WithdrawSubmission struct {
	WithdrawSubmission *v1.WithdrawSubmission `protobuf:"bytes,1004,opt,name=withdraw_submission,json=withdrawSubmission,proto3,oneof"`
}

type SubmitTransactionRequest_ProposalSubmission struct {
	ProposalSubmission *v1.ProposalSubmission `protobuf:"bytes,1005,opt,name=proposal_submission,json=proposalSubmission,proto3,oneof"`
}

type SubmitTransactionRequest_VoteSubmission struct {
	VoteSubmission *v1.VoteSubmission `protobuf:"bytes,1006,opt,name=vote_submission,json=voteSubmission,proto3,oneof"`
}

type SubmitTransactionRequest_LiquidityProvisionSubmission struct {
	LiquidityProvisionSubmission *v1.LiquidityProvisionSubmission `protobuf:"bytes,1007,opt,name=liquidity_provision_submission,json=liquidityProvisionSubmission,proto3,oneof"`
}

type SubmitTransactionRequest_DelegateSubmission struct {
	DelegateSubmission *v1.DelegateSubmission `protobuf:"bytes,1008,opt,name=delegate_submission,json=delegateSubmission,proto3,oneof"`
}

type SubmitTransactionRequest_UndelegateAtEpochEndSubmission struct {
	UndelegateAtEpochEndSubmission *v1.UndelegateAtEpochEndSubmission `protobuf:"bytes,1009,opt,name=undelegate_at_epoch_end_submission,json=undelegateAtEpochEndSubmission,proto3,oneof"`
}

type SubmitTransactionRequest_NodeRegistration struct {
	NodeRegistration *v1.NodeRegistration `protobuf:"bytes,2001,opt,name=node_registration,json=nodeRegistration,proto3,oneof"`
}

type SubmitTransactionRequest_NodeVote struct {
	NodeVote *v1.NodeVote `protobuf:"bytes,2002,opt,name=node_vote,json=nodeVote,proto3,oneof"`
}

type SubmitTransactionRequest_NodeSignature struct {
	NodeSignature *v1.NodeSignature `protobuf:"bytes,2003,opt,name=node_signature,json=nodeSignature,proto3,oneof"`
}

type SubmitTransactionRequest_ChainEvent struct {
	ChainEvent *v1.ChainEvent `protobuf:"bytes,2004,opt,name=chain_event,json=chainEvent,proto3,oneof"`
}

type SubmitTransactionRequest_OracleDataSubmission struct {
	OracleDataSubmission *v1.OracleDataSubmission `protobuf:"bytes,3001,opt,name=oracle_data_submission,json=oracleDataSubmission,proto3,oneof"`
}

func (*SubmitTransactionRequest_OrderSubmission) isSubmitTransactionRequest_Command() {}

func (*SubmitTransactionRequest_OrderCancellation) isSubmitTransactionRequest_Command() {}

func (*SubmitTransactionRequest_OrderAmendment) isSubmitTransactionRequest_Command() {}

func (*SubmitTransactionRequest_WithdrawSubmission) isSubmitTransactionRequest_Command() {}

func (*SubmitTransactionRequest_ProposalSubmission) isSubmitTransactionRequest_Command() {}

func (*SubmitTransactionRequest_VoteSubmission) isSubmitTransactionRequest_Command() {}

func (*SubmitTransactionRequest_LiquidityProvisionSubmission) isSubmitTransactionRequest_Command() {}

func (*SubmitTransactionRequest_DelegateSubmission) isSubmitTransactionRequest_Command() {}

func (*SubmitTransactionRequest_UndelegateAtEpochEndSubmission) isSubmitTransactionRequest_Command() {
}

func (*SubmitTransactionRequest_NodeRegistration) isSubmitTransactionRequest_Command() {}

func (*SubmitTransactionRequest_NodeVote) isSubmitTransactionRequest_Command() {}

func (*SubmitTransactionRequest_NodeSignature) isSubmitTransactionRequest_Command() {}

func (*SubmitTransactionRequest_ChainEvent) isSubmitTransactionRequest_Command() {}

func (*SubmitTransactionRequest_OracleDataSubmission) isSubmitTransactionRequest_Command() {}

func (m *SubmitTransactionRequest) GetCommand() isSubmitTransactionRequest_Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *SubmitTransactionRequest) GetOrderSubmission() *v1.OrderSubmission {
	if x, ok := m.GetCommand().(*SubmitTransactionRequest_OrderSubmission); ok {
		return x.OrderSubmission
	}
	return nil
}

func (m *SubmitTransactionRequest) GetOrderCancellation() *v1.OrderCancellation {
	if x, ok := m.GetCommand().(*SubmitTransactionRequest_OrderCancellation); ok {
		return x.OrderCancellation
	}
	return nil
}

func (m *SubmitTransactionRequest) GetOrderAmendment() *v1.OrderAmendment {
	if x, ok := m.GetCommand().(*SubmitTransactionRequest_OrderAmendment); ok {
		return x.OrderAmendment
	}
	return nil
}

func (m *SubmitTransactionRequest) GetWithdrawSubmission() *v1.WithdrawSubmission {
	if x, ok := m.GetCommand().(*SubmitTransactionRequest_WithdrawSubmission); ok {
		return x.WithdrawSubmission
	}
	return nil
}

func (m *SubmitTransactionRequest) GetProposalSubmission() *v1.ProposalSubmission {
	if x, ok := m.GetCommand().(*SubmitTransactionRequest_ProposalSubmission); ok {
		return x.ProposalSubmission
	}
	return nil
}

func (m *SubmitTransactionRequest) GetVoteSubmission() *v1.VoteSubmission {
	if x, ok := m.GetCommand().(*SubmitTransactionRequest_VoteSubmission); ok {
		return x.VoteSubmission
	}
	return nil
}

func (m *SubmitTransactionRequest) GetLiquidityProvisionSubmission() *v1.LiquidityProvisionSubmission {
	if x, ok := m.GetCommand().(*SubmitTransactionRequest_LiquidityProvisionSubmission); ok {
		return x.LiquidityProvisionSubmission
	}
	return nil
}

func (m *SubmitTransactionRequest) GetDelegateSubmission() *v1.DelegateSubmission {
	if x, ok := m.GetCommand().(*SubmitTransactionRequest_DelegateSubmission); ok {
		return x.DelegateSubmission
	}
	return nil
}

func (m *SubmitTransactionRequest) GetUndelegateAtEpochEndSubmission() *v1.UndelegateAtEpochEndSubmission {
	if x, ok := m.GetCommand().(*SubmitTransactionRequest_UndelegateAtEpochEndSubmission); ok {
		return x.UndelegateAtEpochEndSubmission
	}
	return nil
}

func (m *SubmitTransactionRequest) GetNodeRegistration() *v1.NodeRegistration {
	if x, ok := m.GetCommand().(*SubmitTransactionRequest_NodeRegistration); ok {
		return x.NodeRegistration
	}
	return nil
}

func (m *SubmitTransactionRequest) GetNodeVote() *v1.NodeVote {
	if x, ok := m.GetCommand().(*SubmitTransactionRequest_NodeVote); ok {
		return x.NodeVote
	}
	return nil
}

func (m *SubmitTransactionRequest) GetNodeSignature() *v1.NodeSignature {
	if x, ok := m.GetCommand().(*SubmitTransactionRequest_NodeSignature); ok {
		return x.NodeSignature
	}
	return nil
}

func (m *SubmitTransactionRequest) GetChainEvent() *v1.ChainEvent {
	if x, ok := m.GetCommand().(*SubmitTransactionRequest_ChainEvent); ok {
		return x.ChainEvent
	}
	return nil
}

func (m *SubmitTransactionRequest) GetOracleDataSubmission() *v1.OracleDataSubmission {
	if x, ok := m.GetCommand().(*SubmitTransactionRequest_OracleDataSubmission); ok {
		return x.OracleDataSubmission
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SubmitTransactionRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SubmitTransactionRequest_OrderSubmission)(nil),
		(*SubmitTransactionRequest_OrderCancellation)(nil),
		(*SubmitTransactionRequest_OrderAmendment)(nil),
		(*SubmitTransactionRequest_WithdrawSubmission)(nil),
		(*SubmitTransactionRequest_ProposalSubmission)(nil),
		(*SubmitTransactionRequest_VoteSubmission)(nil),
		(*SubmitTransactionRequest_LiquidityProvisionSubmission)(nil),
		(*SubmitTransactionRequest_DelegateSubmission)(nil),
		(*SubmitTransactionRequest_UndelegateAtEpochEndSubmission)(nil),
		(*SubmitTransactionRequest_NodeRegistration)(nil),
		(*SubmitTransactionRequest_NodeVote)(nil),
		(*SubmitTransactionRequest_NodeSignature)(nil),
		(*SubmitTransactionRequest_ChainEvent)(nil),
		(*SubmitTransactionRequest_OracleDataSubmission)(nil),
	}
}

func init() {
	proto.RegisterType((*SubmitTransactionRequest)(nil), "wallet.vega.wallet.v1.SubmitTransactionRequest")
}

func init() { proto.RegisterFile("proto/wallet/v1/wallet.proto", fileDescriptor_7164113feb7df849) }

var fileDescriptor_7164113feb7df849 = []byte{
	// 641 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x95, 0xdb, 0x6e, 0xd3, 0x30,
	0x18, 0xc7, 0x5b, 0x2e, 0xb6, 0xd5, 0x13, 0x3b, 0x98, 0xc3, 0xa2, 0x69, 0x1a, 0x65, 0x48, 0x50,
	0x86, 0xd6, 0x6a, 0x20, 0x34, 0x71, 0xb9, 0x93, 0xa8, 0x04, 0x82, 0x29, 0x85, 0x21, 0x10, 0x52,
	0xe4, 0xc6, 0x1f, 0x9d, 0x85, 0x6b, 0x67, 0x8e, 0x93, 0x6a, 0x37, 0x5c, 0x22, 0xf1, 0x48, 0x3c,
	0x06, 0x87, 0x97, 0xe0, 0x0c, 0x6f, 0x80, 0x1c, 0x27, 0x25, 0x69, 0x69, 0x7a, 0xf7, 0xe5, 0xdf,
	0xef, 0xff, 0xfb, 0xa7, 0x9f, 0x63, 0x1b, 0xad, 0x05, 0x4a, 0x6a, 0xd9, 0x1a, 0x10, 0xce, 0x41,
	0xb7, 0xe2, 0xed, 0xb4, 0x6a, 0x26, 0x32, 0xbe, 0x94, 0x3e, 0xc5, 0xd0, 0x23, 0xcd, 0xac, 0xde,
	0x5e, 0xad, 0x5b, 0x93, 0x2f, 0xfb, 0x7d, 0x22, 0x68, 0x68, 0x6c, 0x59, 0x6d, 0x8d, 0xab, 0x9b,
	0xe3, 0x1d, 0x31, 0xe1, 0x8c, 0x12, 0x2d, 0x95, 0x37, 0xd2, 0x7b, 0x65, 0xbc, 0x57, 0x2a, 0xe2,
	0x73, 0x48, 0x1b, 0x36, 0xde, 0xcd, 0x23, 0xa7, 0x13, 0x75, 0xfb, 0x4c, 0x3f, 0x51, 0x44, 0x84,
	0xc4, 0xd7, 0x4c, 0x0a, 0x17, 0x4e, 0x23, 0x08, 0x35, 0x5e, 0x41, 0xb3, 0x41, 0xd4, 0xf5, 0x5e,
	0xc3, 0x99, 0x53, 0xad, 0x57, 0x1b, 0x35, 0x77, 0x26, 0x88, 0xba, 0x0f, 0xe0, 0x0c, 0xaf, 0xa1,
	0x5a, 0xa0, 0x64, 0x40, 0x7a, 0x44, 0x83, 0x73, 0xae, 0x5e, 0x6d, 0xcc, 0xb9, 0xff, 0x04, 0x7c,
	0x8c, 0x96, 0xa4, 0xa2, 0xa0, 0xbc, 0xd0, 0x80, 0xc3, 0x90, 0x49, 0xe1, 0x7c, 0x99, 0xad, 0x57,
	0x1b, 0xf3, 0xb7, 0x1b, 0xcd, 0xfc, 0xbf, 0x1e, 0xbe, 0x6c, 0xbc, 0xdd, 0x7c, 0x6c, 0x1c, 0x9d,
	0xa1, 0xa1, 0x5d, 0x71, 0x17, 0x65, 0x51, 0xc2, 0x2f, 0x11, 0xb6, 0x5c, 0x9f, 0x08, 0x1f, 0x38,
	0x27, 0xe6, 0x5d, 0x9d, 0xaf, 0x96, 0xbc, 0x59, 0x4e, 0xde, 0xcf, 0x59, 0xda, 0x15, 0x77, 0x59,
	0x8e, 0x8a, 0xb8, 0x83, 0x6c, 0xa0, 0x47, 0xfa, 0x20, 0x68, 0x1f, 0x84, 0x76, 0xbe, 0x59, 0xf4,
	0x8d, 0x72, 0xf4, 0x6e, 0xd6, 0xdf, 0xae, 0xb8, 0x0b, 0xb2, 0xa0, 0x60, 0x0f, 0x5d, 0x18, 0x30,
	0x7d, 0x42, 0x15, 0x19, 0xe4, 0xa7, 0xf1, 0xdd, 0x82, 0x6f, 0x4d, 0x04, 0x3f, 0x4b, 0x4d, 0x85,
	0x81, 0xe0, 0xc1, 0x98, 0x6a, 0x02, 0xcc, 0xe0, 0x65, 0x48, 0x78, 0x3e, 0xe0, 0xc7, 0xb4, 0x80,
	0xa3, 0xd4, 0x54, 0x0c, 0x08, 0xc6, 0x54, 0x33, 0x96, 0x58, 0x6a, 0xc8, 0xc3, 0x7f, 0x4e, 0x1b,
	0xcb, 0xb1, 0xd4, 0x50, 0x00, 0x2f, 0xc4, 0x05, 0x05, 0xbf, 0x41, 0xeb, 0x9c, 0x9d, 0x46, 0x8c,
	0x32, 0x7d, 0xe6, 0x05, 0x4a, 0xc6, 0xcc, 0xc8, 0xf9, 0x8c, 0x5f, 0x36, 0xe3, 0xee, 0xc4, 0x8c,
	0x87, 0x99, 0xff, 0x28, 0xb3, 0x17, 0x12, 0xd7, 0x78, 0xc9, 0xef, 0x66, 0x6a, 0x14, 0x38, 0x98,
	0xaf, 0x35, 0x1f, 0xfa, 0x7b, 0xda, 0xd4, 0x0e, 0x52, 0x53, 0x71, 0x6a, 0x74, 0x4c, 0xc5, 0x6f,
	0xab, 0x68, 0x23, 0x12, 0xc3, 0x0c, 0xa2, 0x3d, 0x08, 0xa4, 0x7f, 0xe2, 0x81, 0xa0, 0xf9, 0xc0,
	0x3f, 0x36, 0x70, 0x67, 0x62, 0xe0, 0xd3, 0x21, 0x63, 0x57, 0x1f, 0x1a, 0xc2, 0xa1, 0xa0, 0x85,
	0xf0, 0xf5, 0xa8, 0xb4, 0x03, 0x3f, 0x47, 0xcb, 0x42, 0x52, 0xf0, 0x14, 0xf4, 0x58, 0xa8, 0x95,
	0xdd, 0x32, 0x1f, 0x16, 0x93, 0xd8, 0x9b, 0x13, 0x63, 0x1f, 0x49, 0x0a, 0x6e, 0xce, 0xd1, 0xae,
	0xb8, 0x4b, 0x62, 0x44, 0xc3, 0xbb, 0xa8, 0x96, 0xa0, 0xcd, 0xda, 0x3a, 0x1f, 0x2d, 0xf2, 0x6a,
	0x29, 0xd2, 0x7c, 0x17, 0xed, 0x8a, 0x3b, 0x27, 0xd2, 0x1a, 0x1f, 0xa1, 0x85, 0x04, 0x11, 0xb2,
	0x9e, 0x20, 0x3a, 0x52, 0xe0, 0x7c, 0xb2, 0x9c, 0xeb, 0xa5, 0x9c, 0x4e, 0xd6, 0xde, 0xae, 0xb8,
	0xe7, 0x45, 0x5e, 0xc0, 0xf7, 0xd1, 0xbc, 0x7f, 0x42, 0x98, 0xf0, 0x20, 0x36, 0x3b, 0xf8, 0xb3,
	0xc5, 0x5d, 0x9b, 0x88, 0xdb, 0x37, 0xcd, 0x87, 0xb1, 0xdd, 0xbd, 0xc8, 0x1f, 0x3e, 0xe1, 0x57,
	0xe8, 0xb2, 0x3d, 0x29, 0x3d, 0x4a, 0x34, 0xc9, 0x2f, 0xda, 0xfb, 0x95, 0x84, 0xb9, 0x55, 0x72,
	0x2a, 0x18, 0xdf, 0x01, 0xd1, 0xa4, 0xb0, 0x54, 0x17, 0xe5, 0x7f, 0xf4, 0xbd, 0x1a, 0x9a, 0x4d,
	0xbd, 0x7b, 0xf7, 0x5e, 0xec, 0xf8, 0x92, 0x42, 0x02, 0x4c, 0x4e, 0x67, 0x5f, 0xf2, 0x26, 0x93,
	0xad, 0x9e, 0xdc, 0x4a, 0xef, 0x10, 0x26, 0x34, 0x28, 0x41, 0x78, 0x6b, 0xe4, 0x66, 0xe9, 0xce,
	0x24, 0xc2, 0x9d, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x5d, 0x07, 0x96, 0xa1, 0x73, 0x06, 0x00,
	0x00,
}
