// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/vega.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Represents a transaction to be sent to Vega.
type Transaction struct {
	// One of the set of Vega commands (proto marshalled).
	InputData []byte `protobuf:"bytes,1,opt,name=inputData,proto3" json:"inputData,omitempty"`
	// A random number used to provided uniqueness and prevents
	// against replay attack.
	Nonce uint64 `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// The block height associated to the transaction.
	// This should always be current height of the node at the time of sending the Tx.
	// BlockHeight is used as a mechanism for replay protection.
	BlockHeight uint64 `protobuf:"varint,3,opt,name=blockHeight,proto3" json:"blockHeight,omitempty"`
	// The sender of the transaction.
	// Any of the following would be valid:
	//
	// Types that are valid to be assigned to From:
	//	*Transaction_Address
	//	*Transaction_PubKey
	From                 isTransaction_From `protobuf_oneof:"from"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb6b8173ee11af27, []int{0}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetInputData() []byte {
	if m != nil {
		return m.InputData
	}
	return nil
}

func (m *Transaction) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Transaction) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

type isTransaction_From interface {
	isTransaction_From()
}

type Transaction_Address struct {
	Address []byte `protobuf:"bytes,1001,opt,name=address,proto3,oneof"`
}

type Transaction_PubKey struct {
	PubKey []byte `protobuf:"bytes,1002,opt,name=pubKey,proto3,oneof"`
}

func (*Transaction_Address) isTransaction_From() {}

func (*Transaction_PubKey) isTransaction_From() {}

func (m *Transaction) GetFrom() isTransaction_From {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Transaction) GetAddress() []byte {
	if x, ok := m.GetFrom().(*Transaction_Address); ok {
		return x.Address
	}
	return nil
}

func (m *Transaction) GetPubKey() []byte {
	if x, ok := m.GetFrom().(*Transaction_PubKey); ok {
		return x.PubKey
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Transaction) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Transaction_Address)(nil),
		(*Transaction_PubKey)(nil),
	}
}

// A signature to be authenticate a transaction
// and to be verified by the vega network
type Signature struct {
	// The bytes of the signature
	Sig []byte `protobuf:"bytes,1,opt,name=sig,proto3" json:"sig,omitempty"`
	// The algorithm used to create the signature
	Algo string `protobuf:"bytes,2,opt,name=algo,proto3" json:"algo,omitempty"`
	// The version of the signature used to create the signature
	Version              uint64   `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Signature) Reset()         { *m = Signature{} }
func (m *Signature) String() string { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()    {}
func (*Signature) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb6b8173ee11af27, []int{1}
}

func (m *Signature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signature.Unmarshal(m, b)
}
func (m *Signature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signature.Marshal(b, m, deterministic)
}
func (m *Signature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signature.Merge(m, src)
}
func (m *Signature) XXX_Size() int {
	return xxx_messageInfo_Signature.Size(m)
}
func (m *Signature) XXX_DiscardUnknown() {
	xxx_messageInfo_Signature.DiscardUnknown(m)
}

var xxx_messageInfo_Signature proto.InternalMessageInfo

func (m *Signature) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *Signature) GetAlgo() string {
	if m != nil {
		return m.Algo
	}
	return ""
}

func (m *Signature) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

// A bundle of a transaction and it's signature.
type SignedBundle struct {
	// Transaction payload (proto marshalled).
	Tx []byte `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	// The signature authenticating the transaction.
	Sig                  *Signature `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SignedBundle) Reset()         { *m = SignedBundle{} }
func (m *SignedBundle) String() string { return proto.CompactTextString(m) }
func (*SignedBundle) ProtoMessage()    {}
func (*SignedBundle) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb6b8173ee11af27, []int{2}
}

func (m *SignedBundle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedBundle.Unmarshal(m, b)
}
func (m *SignedBundle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedBundle.Marshal(b, m, deterministic)
}
func (m *SignedBundle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedBundle.Merge(m, src)
}
func (m *SignedBundle) XXX_Size() int {
	return xxx_messageInfo_SignedBundle.Size(m)
}
func (m *SignedBundle) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedBundle.DiscardUnknown(m)
}

var xxx_messageInfo_SignedBundle proto.InternalMessageInfo

func (m *SignedBundle) GetTx() []byte {
	if m != nil {
		return m.Tx
	}
	return nil
}

func (m *SignedBundle) GetSig() *Signature {
	if m != nil {
		return m.Sig
	}
	return nil
}

func init() {
	proto.RegisterType((*Transaction)(nil), "vega.Transaction")
	proto.RegisterType((*Signature)(nil), "vega.Signature")
	proto.RegisterType((*SignedBundle)(nil), "vega.SignedBundle")
}

func init() { proto.RegisterFile("proto/vega.proto", fileDescriptor_bb6b8173ee11af27) }

var fileDescriptor_bb6b8173ee11af27 = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x4d, 0x1b, 0x5b, 0x3a, 0x2d, 0x5a, 0x06, 0x0f, 0x2b, 0x7a, 0x88, 0x41, 0xa4, 0x17,
	0x13, 0xd0, 0x27, 0x30, 0x78, 0x28, 0xf4, 0x16, 0x3d, 0x79, 0xdb, 0x24, 0xeb, 0xba, 0xb8, 0xee,
	0x84, 0xcd, 0xa6, 0xd6, 0xe7, 0xf1, 0xe9, 0xf4, 0x29, 0x24, 0xdb, 0x44, 0x3d, 0xcd, 0x3f, 0xff,
	0x0f, 0xdf, 0xfc, 0x0c, 0x2c, 0x6b, 0x4b, 0x8e, 0xd2, 0xad, 0x90, 0x3c, 0xf1, 0x12, 0xc3, 0x4e,
	0xc7, 0x9f, 0x01, 0xcc, 0x1f, 0x2d, 0x37, 0x0d, 0x2f, 0x9d, 0x22, 0x83, 0xe7, 0x30, 0x53, 0xa6,
	0x6e, 0xdd, 0x3d, 0x77, 0x9c, 0x05, 0x51, 0xb0, 0x5a, 0xe4, 0x7f, 0x06, 0x9e, 0xc0, 0xa1, 0x21,
	0x53, 0x0a, 0x36, 0x8a, 0x82, 0x55, 0x98, 0xef, 0x17, 0x8c, 0x60, 0x5e, 0x68, 0x2a, 0x5f, 0xd7,
	0x42, 0xc9, 0x17, 0xc7, 0xc6, 0x3e, 0xfb, 0x6f, 0xe1, 0x19, 0x4c, 0x79, 0x55, 0x59, 0xd1, 0x34,
	0xec, 0x6b, 0xda, 0x41, 0xd7, 0x07, 0xf9, 0xe0, 0xe0, 0x29, 0x4c, 0xea, 0xb6, 0xd8, 0x88, 0x0f,
	0xf6, 0x3d, 0x64, 0xbd, 0x91, 0x4d, 0x20, 0x7c, 0xb6, 0xf4, 0x16, 0x6f, 0x60, 0xf6, 0xa0, 0xa4,
	0xe1, 0xae, 0xb5, 0x02, 0x97, 0x30, 0x6e, 0x94, 0xec, 0xcb, 0x75, 0x12, 0x11, 0x42, 0xae, 0x25,
	0xf9, 0x56, 0xb3, 0xdc, 0x6b, 0x64, 0x30, 0xdd, 0x0a, 0xdb, 0x28, 0x32, 0x7d, 0xa1, 0x61, 0x8d,
	0xef, 0x60, 0xd1, 0xc1, 0x44, 0x95, 0xb5, 0xa6, 0xd2, 0x02, 0x8f, 0x60, 0xe4, 0x76, 0x3d, 0x6e,
	0xe4, 0x76, 0x78, 0xb1, 0xe7, 0x77, 0xb0, 0xf9, 0xcd, 0x71, 0xe2, 0x5f, 0xf6, 0x7b, 0xdd, 0x1f,
	0xcc, 0xae, 0x9e, 0x2e, 0x4b, 0xaa, 0x84, 0xcf, 0xfc, 0x37, 0x4b, 0xd2, 0x89, 0xa2, 0x54, 0xd2,
	0xf5, 0x3b, 0xd7, 0x5a, 0xb8, 0xd4, 0xbb, 0xc5, 0xc4, 0x8f, 0xdb, 0x9f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x7c, 0x0f, 0x1f, 0x02, 0x7e, 0x01, 0x00, 0x00,
}
