// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/commands/v1/commands.proto

package v1

import (
	proto1 "code.vegaprotocol.io/go-wallet/internal/proto"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	_ "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// An order submission is a request to submit or create a new order on Vega
type OrderSubmission struct {
	// Market identifier for the order, required field
	MarketId string `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	// Price for the order, the price is an integer, for example `123456` is a correctly
	// formatted price of `1.23456` assuming market configured to 5 decimal places,
	// , required field for limit orders, however it is not required for market orders
	Price uint64 `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	// Size for the order, for example, in a futures market the size equals the number of contracts, cannot be negative
	Size uint64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	// Side for the order, e.g. SIDE_BUY or SIDE_SELL, required field - See [`Side`](#vega.Side)
	Side proto1.Side `protobuf:"varint,4,opt,name=side,proto3,enum=wallet.vega.Side" json:"side,omitempty"`
	// Time in force indicates how long an order will remain active before it is executed or expires, required field
	// - See [`Order.TimeInForce`](#vega.Order.TimeInForce)
	TimeInForce proto1.Order_TimeInForce `protobuf:"varint,5,opt,name=time_in_force,json=timeInForce,proto3,enum=wallet.vega.Order_TimeInForce" json:"time_in_force,omitempty"`
	// Timestamp for when the order will expire, in nanoseconds since the epoch,
	// required field only for [`Order.TimeInForce`](#vega.Order.TimeInForce)`.TIME_IN_FORCE_GTT`
	// - See [`VegaTimeResponse`](#api.VegaTimeResponse).`timestamp`
	ExpiresAt int64 `protobuf:"varint,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Type for the order, required field - See [`Order.Type`](#vega.Order.Type)
	Type proto1.Order_Type `protobuf:"varint,7,opt,name=type,proto3,enum=wallet.vega.Order_Type" json:"type,omitempty"`
	// Reference given for the order, this is typically used to retrieve an order submitted through consensus, currently
	// set internally by the node to return a unique reference identifier for the order submission
	Reference string `protobuf:"bytes,8,opt,name=reference,proto3" json:"reference,omitempty"`
	// Used to specify the details for a pegged order
	// - See [`PeggedOrder`](#vega.PeggedOrder)
	PeggedOrder          *proto1.PeggedOrder `protobuf:"bytes,9,opt,name=pegged_order,json=peggedOrder,proto3" json:"pegged_order,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *OrderSubmission) Reset()         { *m = OrderSubmission{} }
func (m *OrderSubmission) String() string { return proto.CompactTextString(m) }
func (*OrderSubmission) ProtoMessage()    {}
func (*OrderSubmission) Descriptor() ([]byte, []int) {
	return fileDescriptor_356ec24089d7ddfa, []int{0}
}

func (m *OrderSubmission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderSubmission.Unmarshal(m, b)
}
func (m *OrderSubmission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderSubmission.Marshal(b, m, deterministic)
}
func (m *OrderSubmission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderSubmission.Merge(m, src)
}
func (m *OrderSubmission) XXX_Size() int {
	return xxx_messageInfo_OrderSubmission.Size(m)
}
func (m *OrderSubmission) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderSubmission.DiscardUnknown(m)
}

var xxx_messageInfo_OrderSubmission proto.InternalMessageInfo

func (m *OrderSubmission) GetMarketId() string {
	if m != nil {
		return m.MarketId
	}
	return ""
}

func (m *OrderSubmission) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *OrderSubmission) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *OrderSubmission) GetSide() proto1.Side {
	if m != nil {
		return m.Side
	}
	return proto1.Side_SIDE_UNSPECIFIED
}

func (m *OrderSubmission) GetTimeInForce() proto1.Order_TimeInForce {
	if m != nil {
		return m.TimeInForce
	}
	return proto1.Order_TIME_IN_FORCE_UNSPECIFIED
}

func (m *OrderSubmission) GetExpiresAt() int64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

func (m *OrderSubmission) GetType() proto1.Order_Type {
	if m != nil {
		return m.Type
	}
	return proto1.Order_TYPE_UNSPECIFIED
}

func (m *OrderSubmission) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

func (m *OrderSubmission) GetPeggedOrder() *proto1.PeggedOrder {
	if m != nil {
		return m.PeggedOrder
	}
	return nil
}

// An order cancellation is a request to cancel an existing order on Vega
type OrderCancellation struct {
	// Unique identifier for the order (set by the system after consensus), required field
	OrderId string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// Market identifier for the order, required field
	MarketId             string   `protobuf:"bytes,2,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderCancellation) Reset()         { *m = OrderCancellation{} }
func (m *OrderCancellation) String() string { return proto.CompactTextString(m) }
func (*OrderCancellation) ProtoMessage()    {}
func (*OrderCancellation) Descriptor() ([]byte, []int) {
	return fileDescriptor_356ec24089d7ddfa, []int{1}
}

func (m *OrderCancellation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderCancellation.Unmarshal(m, b)
}
func (m *OrderCancellation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderCancellation.Marshal(b, m, deterministic)
}
func (m *OrderCancellation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderCancellation.Merge(m, src)
}
func (m *OrderCancellation) XXX_Size() int {
	return xxx_messageInfo_OrderCancellation.Size(m)
}
func (m *OrderCancellation) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderCancellation.DiscardUnknown(m)
}

var xxx_messageInfo_OrderCancellation proto.InternalMessageInfo

func (m *OrderCancellation) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *OrderCancellation) GetMarketId() string {
	if m != nil {
		return m.MarketId
	}
	return ""
}

// An order amendment is a request to amend or update an existing order on Vega
type OrderAmendment struct {
	// Order identifier, this is required to find the order and will not be updated, required field
	OrderId string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// Market identifier, this is required to find the order and will not be updated
	MarketId string `protobuf:"bytes,2,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	// Amend the price for the order, if the Price value is set, otherwise price will remain unchanged - See [`Price`](#vega.Price)
	Price *proto1.Price `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	// Amend the size for the order by the delta specified:
	// - To reduce the size from the current value set a negative integer value
	// - To increase the size from the current value, set a positive integer value
	// - To leave the size unchanged set a value of zero
	SizeDelta int64 `protobuf:"varint,4,opt,name=size_delta,json=sizeDelta,proto3" json:"size_delta,omitempty"`
	// Amend the expiry time for the order, if the Timestamp value is set, otherwise expiry time will remain unchanged
	// - See [`VegaTimeResponse`](#api.VegaTimeResponse).`timestamp`
	ExpiresAt *proto1.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Amend the time in force for the order, set to TIME_IN_FORCE_UNSPECIFIED to remain unchanged
	// - See [`TimeInForce`](#api.VegaTimeResponse).`timestamp`
	TimeInForce proto1.Order_TimeInForce `protobuf:"varint,6,opt,name=time_in_force,json=timeInForce,proto3,enum=wallet.vega.Order_TimeInForce" json:"time_in_force,omitempty"`
	// Amend the pegged order offset for the order
	PeggedOffset *wrappers.Int64Value `protobuf:"bytes,7,opt,name=pegged_offset,json=peggedOffset,proto3" json:"pegged_offset,omitempty"`
	// Amend the pegged order reference for the order
	// - See [`PeggedReference`](#vega.PeggedReference)
	PeggedReference      proto1.PeggedReference `protobuf:"varint,8,opt,name=pegged_reference,json=peggedReference,proto3,enum=wallet.vega.PeggedReference" json:"pegged_reference,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *OrderAmendment) Reset()         { *m = OrderAmendment{} }
func (m *OrderAmendment) String() string { return proto.CompactTextString(m) }
func (*OrderAmendment) ProtoMessage()    {}
func (*OrderAmendment) Descriptor() ([]byte, []int) {
	return fileDescriptor_356ec24089d7ddfa, []int{2}
}

func (m *OrderAmendment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderAmendment.Unmarshal(m, b)
}
func (m *OrderAmendment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderAmendment.Marshal(b, m, deterministic)
}
func (m *OrderAmendment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderAmendment.Merge(m, src)
}
func (m *OrderAmendment) XXX_Size() int {
	return xxx_messageInfo_OrderAmendment.Size(m)
}
func (m *OrderAmendment) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderAmendment.DiscardUnknown(m)
}

var xxx_messageInfo_OrderAmendment proto.InternalMessageInfo

func (m *OrderAmendment) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *OrderAmendment) GetMarketId() string {
	if m != nil {
		return m.MarketId
	}
	return ""
}

func (m *OrderAmendment) GetPrice() *proto1.Price {
	if m != nil {
		return m.Price
	}
	return nil
}

func (m *OrderAmendment) GetSizeDelta() int64 {
	if m != nil {
		return m.SizeDelta
	}
	return 0
}

func (m *OrderAmendment) GetExpiresAt() *proto1.Timestamp {
	if m != nil {
		return m.ExpiresAt
	}
	return nil
}

func (m *OrderAmendment) GetTimeInForce() proto1.Order_TimeInForce {
	if m != nil {
		return m.TimeInForce
	}
	return proto1.Order_TIME_IN_FORCE_UNSPECIFIED
}

func (m *OrderAmendment) GetPeggedOffset() *wrappers.Int64Value {
	if m != nil {
		return m.PeggedOffset
	}
	return nil
}

func (m *OrderAmendment) GetPeggedReference() proto1.PeggedReference {
	if m != nil {
		return m.PeggedReference
	}
	return proto1.PeggedReference_PEGGED_REFERENCE_UNSPECIFIED
}

// A liquidity provision submitted for a given market
type LiquidityProvisionSubmission struct {
	// Market identifier for the order, required field
	MarketId string `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	// Specified as a unitless number that represents the amount of settlement asset of the market
	CommitmentAmount uint64 `protobuf:"varint,2,opt,name=commitment_amount,json=commitmentAmount,proto3" json:"commitment_amount,omitempty"`
	// Nominated liquidity fee factor, which is an input to the calculation of taker fees on the market, as per seeting fees and rewarding liquidity providers
	Fee string `protobuf:"bytes,3,opt,name=fee,proto3" json:"fee,omitempty"`
	// A set of liquidity sell orders to meet the liquidity provision obligation
	Sells []*proto1.LiquidityOrder `protobuf:"bytes,4,rep,name=sells,proto3" json:"sells,omitempty"`
	// A set of liquidity buy orders to meet the liquidity provision obligation
	Buys []*proto1.LiquidityOrder `protobuf:"bytes,5,rep,name=buys,proto3" json:"buys,omitempty"`
	// A reference to be added to every order created out of this liquidityProvisionSubmission
	Reference            string   `protobuf:"bytes,6,opt,name=reference,proto3" json:"reference,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LiquidityProvisionSubmission) Reset()         { *m = LiquidityProvisionSubmission{} }
func (m *LiquidityProvisionSubmission) String() string { return proto.CompactTextString(m) }
func (*LiquidityProvisionSubmission) ProtoMessage()    {}
func (*LiquidityProvisionSubmission) Descriptor() ([]byte, []int) {
	return fileDescriptor_356ec24089d7ddfa, []int{3}
}

func (m *LiquidityProvisionSubmission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LiquidityProvisionSubmission.Unmarshal(m, b)
}
func (m *LiquidityProvisionSubmission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LiquidityProvisionSubmission.Marshal(b, m, deterministic)
}
func (m *LiquidityProvisionSubmission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiquidityProvisionSubmission.Merge(m, src)
}
func (m *LiquidityProvisionSubmission) XXX_Size() int {
	return xxx_messageInfo_LiquidityProvisionSubmission.Size(m)
}
func (m *LiquidityProvisionSubmission) XXX_DiscardUnknown() {
	xxx_messageInfo_LiquidityProvisionSubmission.DiscardUnknown(m)
}

var xxx_messageInfo_LiquidityProvisionSubmission proto.InternalMessageInfo

func (m *LiquidityProvisionSubmission) GetMarketId() string {
	if m != nil {
		return m.MarketId
	}
	return ""
}

func (m *LiquidityProvisionSubmission) GetCommitmentAmount() uint64 {
	if m != nil {
		return m.CommitmentAmount
	}
	return 0
}

func (m *LiquidityProvisionSubmission) GetFee() string {
	if m != nil {
		return m.Fee
	}
	return ""
}

func (m *LiquidityProvisionSubmission) GetSells() []*proto1.LiquidityOrder {
	if m != nil {
		return m.Sells
	}
	return nil
}

func (m *LiquidityProvisionSubmission) GetBuys() []*proto1.LiquidityOrder {
	if m != nil {
		return m.Buys
	}
	return nil
}

func (m *LiquidityProvisionSubmission) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

// Represents the submission request to withdraw funds for a party on Vega
type WithdrawSubmission struct {
	// The amount to be withdrawn
	Amount uint64 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	// The asset we want to withdraw
	Asset string `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	// Foreign chain specifics
	Ext                  *proto1.WithdrawExt `protobuf:"bytes,3,opt,name=ext,proto3" json:"ext,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *WithdrawSubmission) Reset()         { *m = WithdrawSubmission{} }
func (m *WithdrawSubmission) String() string { return proto.CompactTextString(m) }
func (*WithdrawSubmission) ProtoMessage()    {}
func (*WithdrawSubmission) Descriptor() ([]byte, []int) {
	return fileDescriptor_356ec24089d7ddfa, []int{4}
}

func (m *WithdrawSubmission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawSubmission.Unmarshal(m, b)
}
func (m *WithdrawSubmission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawSubmission.Marshal(b, m, deterministic)
}
func (m *WithdrawSubmission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawSubmission.Merge(m, src)
}
func (m *WithdrawSubmission) XXX_Size() int {
	return xxx_messageInfo_WithdrawSubmission.Size(m)
}
func (m *WithdrawSubmission) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawSubmission.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawSubmission proto.InternalMessageInfo

func (m *WithdrawSubmission) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *WithdrawSubmission) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *WithdrawSubmission) GetExt() *proto1.WithdrawExt {
	if m != nil {
		return m.Ext
	}
	return nil
}

// A command to submit a new proposal for the
// vega network governance
type ProposalSubmission struct {
	// Proposal reference
	Reference string `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	// Proposal configuration and the actual change that is meant to be executed when proposal is enacted
	Terms                *proto1.ProposalTerms `protobuf:"bytes,2,opt,name=terms,proto3" json:"terms,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ProposalSubmission) Reset()         { *m = ProposalSubmission{} }
func (m *ProposalSubmission) String() string { return proto.CompactTextString(m) }
func (*ProposalSubmission) ProtoMessage()    {}
func (*ProposalSubmission) Descriptor() ([]byte, []int) {
	return fileDescriptor_356ec24089d7ddfa, []int{5}
}

func (m *ProposalSubmission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProposalSubmission.Unmarshal(m, b)
}
func (m *ProposalSubmission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProposalSubmission.Marshal(b, m, deterministic)
}
func (m *ProposalSubmission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProposalSubmission.Merge(m, src)
}
func (m *ProposalSubmission) XXX_Size() int {
	return xxx_messageInfo_ProposalSubmission.Size(m)
}
func (m *ProposalSubmission) XXX_DiscardUnknown() {
	xxx_messageInfo_ProposalSubmission.DiscardUnknown(m)
}

var xxx_messageInfo_ProposalSubmission proto.InternalMessageInfo

func (m *ProposalSubmission) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

func (m *ProposalSubmission) GetTerms() *proto1.ProposalTerms {
	if m != nil {
		return m.Terms
	}
	return nil
}

// A command to submit a new vote for a governance
// proposal.
type VoteSubmission struct {
	// The ID of the proposal to vote for.
	ProposalId string `protobuf:"bytes,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	// The actual value of the vote
	Value                proto1.Vote_Value `protobuf:"varint,2,opt,name=value,proto3,enum=wallet.vega.Vote_Value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *VoteSubmission) Reset()         { *m = VoteSubmission{} }
func (m *VoteSubmission) String() string { return proto.CompactTextString(m) }
func (*VoteSubmission) ProtoMessage()    {}
func (*VoteSubmission) Descriptor() ([]byte, []int) {
	return fileDescriptor_356ec24089d7ddfa, []int{6}
}

func (m *VoteSubmission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteSubmission.Unmarshal(m, b)
}
func (m *VoteSubmission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteSubmission.Marshal(b, m, deterministic)
}
func (m *VoteSubmission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteSubmission.Merge(m, src)
}
func (m *VoteSubmission) XXX_Size() int {
	return xxx_messageInfo_VoteSubmission.Size(m)
}
func (m *VoteSubmission) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteSubmission.DiscardUnknown(m)
}

var xxx_messageInfo_VoteSubmission proto.InternalMessageInfo

func (m *VoteSubmission) GetProposalId() string {
	if m != nil {
		return m.ProposalId
	}
	return ""
}

func (m *VoteSubmission) GetValue() proto1.Vote_Value {
	if m != nil {
		return m.Value
	}
	return proto1.Vote_VALUE_UNSPECIFIED
}

// A command to submit an instruction to delegate some stake to a node
type DelegateSubmission struct {
	// The ID for the node to delegate to
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// The amount of stake to delegate
	Amount               uint64   `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelegateSubmission) Reset()         { *m = DelegateSubmission{} }
func (m *DelegateSubmission) String() string { return proto.CompactTextString(m) }
func (*DelegateSubmission) ProtoMessage()    {}
func (*DelegateSubmission) Descriptor() ([]byte, []int) {
	return fileDescriptor_356ec24089d7ddfa, []int{7}
}

func (m *DelegateSubmission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelegateSubmission.Unmarshal(m, b)
}
func (m *DelegateSubmission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelegateSubmission.Marshal(b, m, deterministic)
}
func (m *DelegateSubmission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelegateSubmission.Merge(m, src)
}
func (m *DelegateSubmission) XXX_Size() int {
	return xxx_messageInfo_DelegateSubmission.Size(m)
}
func (m *DelegateSubmission) XXX_DiscardUnknown() {
	xxx_messageInfo_DelegateSubmission.DiscardUnknown(m)
}

var xxx_messageInfo_DelegateSubmission proto.InternalMessageInfo

func (m *DelegateSubmission) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *DelegateSubmission) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

// A command to submit an instruction to undelete stake from a node
type UndelegateAtEpochEndSubmission struct {
	// The ID for the node to undelegate from
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// The amount of stake to undelegate
	Amount               uint64   `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UndelegateAtEpochEndSubmission) Reset()         { *m = UndelegateAtEpochEndSubmission{} }
func (m *UndelegateAtEpochEndSubmission) String() string { return proto.CompactTextString(m) }
func (*UndelegateAtEpochEndSubmission) ProtoMessage()    {}
func (*UndelegateAtEpochEndSubmission) Descriptor() ([]byte, []int) {
	return fileDescriptor_356ec24089d7ddfa, []int{8}
}

func (m *UndelegateAtEpochEndSubmission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UndelegateAtEpochEndSubmission.Unmarshal(m, b)
}
func (m *UndelegateAtEpochEndSubmission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UndelegateAtEpochEndSubmission.Marshal(b, m, deterministic)
}
func (m *UndelegateAtEpochEndSubmission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UndelegateAtEpochEndSubmission.Merge(m, src)
}
func (m *UndelegateAtEpochEndSubmission) XXX_Size() int {
	return xxx_messageInfo_UndelegateAtEpochEndSubmission.Size(m)
}
func (m *UndelegateAtEpochEndSubmission) XXX_DiscardUnknown() {
	xxx_messageInfo_UndelegateAtEpochEndSubmission.DiscardUnknown(m)
}

var xxx_messageInfo_UndelegateAtEpochEndSubmission proto.InternalMessageInfo

func (m *UndelegateAtEpochEndSubmission) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *UndelegateAtEpochEndSubmission) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func init() {
	proto.RegisterType((*OrderSubmission)(nil), "wallet.vega.commands.v1.OrderSubmission")
	proto.RegisterType((*OrderCancellation)(nil), "wallet.vega.commands.v1.OrderCancellation")
	proto.RegisterType((*OrderAmendment)(nil), "wallet.vega.commands.v1.OrderAmendment")
	proto.RegisterType((*LiquidityProvisionSubmission)(nil), "wallet.vega.commands.v1.LiquidityProvisionSubmission")
	proto.RegisterType((*WithdrawSubmission)(nil), "wallet.vega.commands.v1.WithdrawSubmission")
	proto.RegisterType((*ProposalSubmission)(nil), "wallet.vega.commands.v1.ProposalSubmission")
	proto.RegisterType((*VoteSubmission)(nil), "wallet.vega.commands.v1.VoteSubmission")
	proto.RegisterType((*DelegateSubmission)(nil), "wallet.vega.commands.v1.DelegateSubmission")
	proto.RegisterType((*UndelegateAtEpochEndSubmission)(nil), "wallet.vega.commands.v1.UndelegateAtEpochEndSubmission")
}

func init() { proto.RegisterFile("proto/commands/v1/commands.proto", fileDescriptor_356ec24089d7ddfa) }

var fileDescriptor_356ec24089d7ddfa = []byte{
	// 851 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x5f, 0x6f, 0x1b, 0x45,
	0x10, 0xe7, 0xfc, 0x2f, 0xf1, 0x98, 0xa6, 0xce, 0x0a, 0xa5, 0x87, 0x9b, 0xa6, 0xc6, 0x08, 0x61,
	0x51, 0xe5, 0x4e, 0x31, 0x50, 0x81, 0xfa, 0x42, 0x42, 0x03, 0xb2, 0x00, 0x35, 0xda, 0x96, 0xf2,
	0xe7, 0xc5, 0x5a, 0x7b, 0xc7, 0x97, 0x55, 0xef, 0x6e, 0x8f, 0xbd, 0xb5, 0x9d, 0xf0, 0xcc, 0xf7,
	0xe0, 0xa3, 0x21, 0xf1, 0x31, 0x78, 0x42, 0xbb, 0x7b, 0x76, 0xee, 0x9c, 0x4a, 0x50, 0xa9, 0x6f,
	0x3b, 0xff, 0x7e, 0xb3, 0x33, 0xbf, 0x99, 0x5d, 0xe8, 0x67, 0x4a, 0x6a, 0x19, 0xce, 0x64, 0x92,
	0xb0, 0x94, 0xe7, 0xe1, 0xf2, 0x64, 0x73, 0x0e, 0xac, 0x89, 0xdc, 0x5b, 0xb1, 0x38, 0x46, 0x1d,
	0x2c, 0x31, 0x62, 0xc1, 0xc6, 0xb6, 0x3c, 0xe9, 0x1d, 0xb8, 0xd0, 0x48, 0x2e, 0x51, 0xa5, 0x2c,
	0x9d, 0xa1, 0x0b, 0xe8, 0x75, 0x9d, 0xde, 0xfa, 0x3b, 0xcd, 0x51, 0x24, 0x65, 0x14, 0x63, 0x68,
	0xa5, 0xe9, 0x62, 0x1e, 0xae, 0x14, 0xcb, 0x32, 0x54, 0x45, 0x8a, 0xde, 0xe3, 0x48, 0xe8, 0xcb,
	0xc5, 0xd4, 0xa0, 0x87, 0xc9, 0x4a, 0xe8, 0x57, 0x72, 0x15, 0x46, 0xf2, 0xd8, 0x1a, 0x8f, 0x97,
	0x2c, 0x16, 0x9c, 0x69, 0xa9, 0xf2, 0x70, 0x73, 0x74, 0x71, 0x83, 0x7f, 0x6a, 0x70, 0xf7, 0x99,
	0xe2, 0xa8, 0x9e, 0x2f, 0xa6, 0x89, 0xc8, 0x73, 0x21, 0x53, 0xf2, 0x21, 0xb4, 0x13, 0xa6, 0x5e,
	0xa1, 0x9e, 0x08, 0xee, 0x7b, 0x7d, 0x6f, 0xd8, 0x3e, 0x6b, 0xfd, 0xfd, 0xd7, 0xc3, 0xda, 0xcf,
	0x1e, 0xdd, 0x75, 0x86, 0x31, 0x27, 0xef, 0x41, 0x33, 0x53, 0x62, 0x86, 0x7e, 0xad, 0xef, 0x0d,
	0x1b, 0xd4, 0x09, 0xa4, 0x07, 0x8d, 0x5c, 0xfc, 0x8e, 0x7e, 0xdd, 0x28, 0x5d, 0x54, 0xf7, 0x1d,
	0x6a, 0x75, 0xe4, 0x23, 0x63, 0xe3, 0xe8, 0x37, 0xfa, 0xde, 0x70, 0x6f, 0xb4, 0x1f, 0x94, 0x9b,
	0xf2, 0x5c, 0x70, 0xa4, 0xd6, 0x4c, 0xce, 0xe0, 0x8e, 0x16, 0x09, 0x4e, 0x44, 0x3a, 0x99, 0x4b,
	0x35, 0x43, 0xbf, 0x69, 0xfd, 0x8f, 0x2a, 0xfe, 0xf6, 0xca, 0xc1, 0x0b, 0x91, 0xe0, 0x38, 0xfd,
	0xc6, 0x78, 0xd1, 0x8e, 0xbe, 0x11, 0xc8, 0x03, 0x00, 0xbc, 0xca, 0x84, 0xc2, 0x7c, 0xc2, 0xb4,
	0xdf, 0xea, 0x7b, 0xc3, 0x3a, 0x6d, 0x17, 0x9a, 0x53, 0x4d, 0x1e, 0x41, 0x43, 0x5f, 0x67, 0xe8,
	0xef, 0x58, 0xe4, 0x7b, 0xaf, 0x43, 0xbe, 0xce, 0x90, 0x5a, 0x27, 0x72, 0x08, 0x6d, 0x85, 0x73,
	0x54, 0x98, 0xce, 0xd0, 0xdf, 0x35, 0xdd, 0xa0, 0x37, 0x0a, 0xf2, 0x04, 0xde, 0xcd, 0x30, 0x8a,
	0x90, 0x4f, 0xa4, 0x09, 0xf4, 0xdb, 0x7d, 0x6f, 0xd8, 0x19, 0xf9, 0x15, 0xc8, 0x0b, 0xeb, 0x60,
	0x81, 0x69, 0x27, 0xbb, 0x11, 0x06, 0xdf, 0xc1, 0xbe, 0x3d, 0x7c, 0x6d, 0xa8, 0x8f, 0x63, 0xa6,
	0x4d, 0xf7, 0xdf, 0x87, 0x5d, 0x0b, 0xb5, 0x69, 0x3e, 0xdd, 0xb1, 0xf2, 0x98, 0x93, 0xfb, 0x65,
	0x62, 0x6a, 0xd6, 0xb6, 0x21, 0x64, 0xf0, 0x67, 0x1d, 0xf6, 0x2c, 0xda, 0x69, 0x82, 0x29, 0x4f,
	0x30, 0xd5, 0xe4, 0x83, 0x6d, 0xa8, 0x0d, 0x8f, 0xff, 0x0b, 0x92, 0x0c, 0xd7, 0x1c, 0xd7, 0x6d,
	0x55, 0xa4, 0x5a, 0x95, 0xb1, 0xac, 0x79, 0x7f, 0x00, 0x60, 0x38, 0x9e, 0x70, 0x8c, 0x35, 0xb3,
	0x0c, 0xd7, 0x69, 0xdb, 0x68, 0x9e, 0x1a, 0x05, 0xf9, 0xbc, 0xc2, 0x47, 0xd3, 0xa2, 0x1d, 0x54,
	0xd0, 0x0c, 0x95, 0xb9, 0x66, 0x49, 0x56, 0xe6, 0xe9, 0xd6, 0x28, 0xb4, 0xde, 0x7c, 0x14, 0xbe,
	0x82, 0x3b, 0x6b, 0x82, 0xe6, 0xf3, 0x1c, 0xb5, 0x25, 0xbd, 0x33, 0xba, 0x1f, 0xb8, 0x85, 0x0a,
	0xd6, 0x0b, 0x15, 0x8c, 0x53, 0xfd, 0xf8, 0xb3, 0x97, 0x2c, 0x5e, 0x20, 0x2d, 0x28, 0x7d, 0x66,
	0x03, 0xc8, 0xb7, 0xd0, 0x2d, 0x10, 0xaa, 0x73, 0xb0, 0x37, 0x3a, 0x7c, 0x0d, 0xcd, 0x74, 0xed,
	0x43, 0xef, 0x66, 0x55, 0xc5, 0xe0, 0x8f, 0x1a, 0x1c, 0x7e, 0x2f, 0x7e, 0x5b, 0x08, 0x2e, 0xf4,
	0xf5, 0x85, 0x92, 0x4b, 0x61, 0xd6, 0xed, 0x4d, 0x17, 0xef, 0x11, 0xec, 0x9b, 0x27, 0x44, 0x68,
	0x43, 0xf1, 0x84, 0x25, 0x72, 0x91, 0xea, 0x62, 0x09, 0xbb, 0x37, 0x86, 0x53, 0xab, 0x27, 0x5d,
	0xa8, 0xcf, 0xd1, 0xf1, 0xd7, 0xa6, 0xe6, 0x48, 0x4e, 0xa0, 0x99, 0x63, 0x1c, 0xe7, 0x7e, 0xa3,
	0x5f, 0xb7, 0x7d, 0x28, 0x97, 0xb0, 0xb9, 0x9d, 0x1b, 0x56, 0xe7, 0x49, 0x42, 0x68, 0x4c, 0x17,
	0xd7, 0xb9, 0xdf, 0xfc, 0xef, 0x08, 0xeb, 0x58, 0x5d, 0x99, 0xd6, 0xd6, 0xca, 0x0c, 0x52, 0x20,
	0x3f, 0x09, 0x7d, 0xc9, 0x15, 0x5b, 0x95, 0x6a, 0x3f, 0x80, 0x56, 0x51, 0x8b, 0x67, 0x6b, 0x29,
	0x24, 0xf3, 0xce, 0xb0, 0xdc, 0xf0, 0xe6, 0x86, 0xd3, 0x09, 0xe4, 0x13, 0xa8, 0xe3, 0x95, 0x2e,
	0xe6, 0xb2, 0xba, 0x6d, 0x6b, 0xec, 0xf3, 0x2b, 0x4d, 0x8d, 0xd3, 0x20, 0x06, 0x72, 0xa1, 0x64,
	0x26, 0x73, 0x16, 0x97, 0xf2, 0x55, 0xee, 0xe8, 0x6d, 0xaf, 0xf5, 0x17, 0xd0, 0xd4, 0xa8, 0x92,
	0xdc, 0x66, 0xed, 0x8c, 0x7a, 0x5b, 0x93, 0xef, 0xd0, 0x5e, 0x18, 0x0f, 0xc7, 0x50, 0xdf, 0xa3,
	0x2e, 0x60, 0x70, 0x09, 0x7b, 0x2f, 0xa5, 0xc6, 0x52, 0xa6, 0x8f, 0xa1, 0x93, 0x15, 0x11, 0xb7,
	0x79, 0x85, 0xb5, 0x69, 0xcc, 0xc9, 0x31, 0x34, 0x97, 0x66, 0xfe, 0x6c, 0xd2, 0xed, 0x77, 0xc9,
	0x80, 0x06, 0x6e, 0x3c, 0x9d, 0xd7, 0xe0, 0x07, 0x20, 0x4f, 0x31, 0xc6, 0x88, 0x55, 0xb2, 0x3d,
	0x84, 0x9d, 0x54, 0x72, 0xbc, 0x9d, 0xa9, 0x65, 0xd4, 0x63, 0x5e, 0x6a, 0x74, 0xad, 0xdc, 0xe8,
	0xc1, 0x2f, 0x70, 0xf4, 0x63, 0xca, 0x0b, 0xc0, 0x53, 0x7d, 0x9e, 0xc9, 0xd9, 0xe5, 0x79, 0xca,
	0xdf, 0x02, 0xf4, 0xd9, 0x93, 0x5f, 0xbf, 0x9c, 0x49, 0x8e, 0xb6, 0x10, 0xbb, 0x6f, 0x33, 0x19,
	0x07, 0xc2, 0xfc, 0x7b, 0xc7, 0xae, 0xc4, 0x50, 0xa4, 0xda, 0xfc, 0x80, 0x71, 0x78, 0xeb, 0x2f,
	0x9d, 0xb6, 0xac, 0xea, 0xd3, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xd4, 0x7d, 0x71, 0xb7, 0x67,
	0x07, 0x00, 0x00,
}
