// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/commands/v1/validator_commands.proto

package v1

import (
	proto1 "code.vegaprotocol.io/go-wallet/internal/proto"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The kind of the signature created by a node, for example, allow-listing a new asset, withdrawal etc
type NodeSignatureKind int32

const (
	// Represents an unspecified or missing value from the input
	NodeSignatureKind_NODE_SIGNATURE_KIND_UNSPECIFIED NodeSignatureKind = 0
	// Represents a signature for a new asset allow-listing
	NodeSignatureKind_NODE_SIGNATURE_KIND_ASSET_NEW NodeSignatureKind = 1
	// Represents a signature for an asset withdrawal
	NodeSignatureKind_NODE_SIGNATURE_KIND_ASSET_WITHDRAWAL NodeSignatureKind = 2
)

var NodeSignatureKind_name = map[int32]string{
	0: "NODE_SIGNATURE_KIND_UNSPECIFIED",
	1: "NODE_SIGNATURE_KIND_ASSET_NEW",
	2: "NODE_SIGNATURE_KIND_ASSET_WITHDRAWAL",
}

var NodeSignatureKind_value = map[string]int32{
	"NODE_SIGNATURE_KIND_UNSPECIFIED":      0,
	"NODE_SIGNATURE_KIND_ASSET_NEW":        1,
	"NODE_SIGNATURE_KIND_ASSET_WITHDRAWAL": 2,
}

func (x NodeSignatureKind) String() string {
	return proto.EnumName(NodeSignatureKind_name, int32(x))
}

func (NodeSignatureKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3bd0a30d86c3d00b, []int{0}
}

// Used to Register a node as a validator during network start-up
type NodeRegistration struct {
	// Public key, required field
	PubKey []byte `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	// Public key for the blockchain, required field
	ChainPubKey          []byte   `protobuf:"bytes,2,opt,name=chain_pub_key,json=chainPubKey,proto3" json:"chain_pub_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeRegistration) Reset()         { *m = NodeRegistration{} }
func (m *NodeRegistration) String() string { return proto.CompactTextString(m) }
func (*NodeRegistration) ProtoMessage()    {}
func (*NodeRegistration) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bd0a30d86c3d00b, []int{0}
}

func (m *NodeRegistration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeRegistration.Unmarshal(m, b)
}
func (m *NodeRegistration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeRegistration.Marshal(b, m, deterministic)
}
func (m *NodeRegistration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeRegistration.Merge(m, src)
}
func (m *NodeRegistration) XXX_Size() int {
	return xxx_messageInfo_NodeRegistration.Size(m)
}
func (m *NodeRegistration) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeRegistration.DiscardUnknown(m)
}

var xxx_messageInfo_NodeRegistration proto.InternalMessageInfo

func (m *NodeRegistration) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *NodeRegistration) GetChainPubKey() []byte {
	if m != nil {
		return m.ChainPubKey
	}
	return nil
}

// Used when a node votes for validating a given resource exists or is valid,
// for example, an ERC20 deposit is valid and exists on ethereum
type NodeVote struct {
	// Public key, required field
	PubKey []byte `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	// Reference, required field
	Reference            string   `protobuf:"bytes,2,opt,name=reference,proto3" json:"reference,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeVote) Reset()         { *m = NodeVote{} }
func (m *NodeVote) String() string { return proto.CompactTextString(m) }
func (*NodeVote) ProtoMessage()    {}
func (*NodeVote) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bd0a30d86c3d00b, []int{1}
}

func (m *NodeVote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeVote.Unmarshal(m, b)
}
func (m *NodeVote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeVote.Marshal(b, m, deterministic)
}
func (m *NodeVote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeVote.Merge(m, src)
}
func (m *NodeVote) XXX_Size() int {
	return xxx_messageInfo_NodeVote.Size(m)
}
func (m *NodeVote) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeVote.DiscardUnknown(m)
}

var xxx_messageInfo_NodeVote proto.InternalMessageInfo

func (m *NodeVote) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *NodeVote) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

// Represents a signature from a validator, to be used by a foreign chain in order to recognise a decision taken by the Vega network
type NodeSignature struct {
	// The identifier of the resource being signed
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The signature
	Sig []byte `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	// The kind of resource being signed
	Kind                 NodeSignatureKind `protobuf:"varint,3,opt,name=kind,proto3,enum=wallet.vega.commands.v1.NodeSignatureKind" json:"kind,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *NodeSignature) Reset()         { *m = NodeSignature{} }
func (m *NodeSignature) String() string { return proto.CompactTextString(m) }
func (*NodeSignature) ProtoMessage()    {}
func (*NodeSignature) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bd0a30d86c3d00b, []int{2}
}

func (m *NodeSignature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeSignature.Unmarshal(m, b)
}
func (m *NodeSignature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeSignature.Marshal(b, m, deterministic)
}
func (m *NodeSignature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeSignature.Merge(m, src)
}
func (m *NodeSignature) XXX_Size() int {
	return xxx_messageInfo_NodeSignature.Size(m)
}
func (m *NodeSignature) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeSignature.DiscardUnknown(m)
}

var xxx_messageInfo_NodeSignature proto.InternalMessageInfo

func (m *NodeSignature) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NodeSignature) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *NodeSignature) GetKind() NodeSignatureKind {
	if m != nil {
		return m.Kind
	}
	return NodeSignatureKind_NODE_SIGNATURE_KIND_UNSPECIFIED
}

// An event forwarded to the Vega network to provide information on events happening on other networks
type ChainEvent struct {
	// The identifier of the transaction in which the events happened, usually a hash
	TxId string `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	// Arbitrary one-time integer used to prevent replay attacks
	Nonce uint64 `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// The event
	//
	// Types that are valid to be assigned to Event:
	//	*ChainEvent_Builtin
	//	*ChainEvent_Erc20
	//	*ChainEvent_Btc
	//	*ChainEvent_Validator
	Event                isChainEvent_Event `protobuf_oneof:"event"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ChainEvent) Reset()         { *m = ChainEvent{} }
func (m *ChainEvent) String() string { return proto.CompactTextString(m) }
func (*ChainEvent) ProtoMessage()    {}
func (*ChainEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bd0a30d86c3d00b, []int{3}
}

func (m *ChainEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainEvent.Unmarshal(m, b)
}
func (m *ChainEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainEvent.Marshal(b, m, deterministic)
}
func (m *ChainEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainEvent.Merge(m, src)
}
func (m *ChainEvent) XXX_Size() int {
	return xxx_messageInfo_ChainEvent.Size(m)
}
func (m *ChainEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ChainEvent proto.InternalMessageInfo

func (m *ChainEvent) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func (m *ChainEvent) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

type isChainEvent_Event interface {
	isChainEvent_Event()
}

type ChainEvent_Builtin struct {
	Builtin *proto1.BuiltinAssetEvent `protobuf:"bytes,1001,opt,name=builtin,proto3,oneof"`
}

type ChainEvent_Erc20 struct {
	Erc20 *proto1.ERC20Event `protobuf:"bytes,1002,opt,name=erc20,proto3,oneof"`
}

type ChainEvent_Btc struct {
	Btc *proto1.BTCEvent `protobuf:"bytes,1003,opt,name=btc,proto3,oneof"`
}

type ChainEvent_Validator struct {
	Validator *proto1.ValidatorEvent `protobuf:"bytes,1004,opt,name=validator,proto3,oneof"`
}

func (*ChainEvent_Builtin) isChainEvent_Event() {}

func (*ChainEvent_Erc20) isChainEvent_Event() {}

func (*ChainEvent_Btc) isChainEvent_Event() {}

func (*ChainEvent_Validator) isChainEvent_Event() {}

func (m *ChainEvent) GetEvent() isChainEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *ChainEvent) GetBuiltin() *proto1.BuiltinAssetEvent {
	if x, ok := m.GetEvent().(*ChainEvent_Builtin); ok {
		return x.Builtin
	}
	return nil
}

func (m *ChainEvent) GetErc20() *proto1.ERC20Event {
	if x, ok := m.GetEvent().(*ChainEvent_Erc20); ok {
		return x.Erc20
	}
	return nil
}

func (m *ChainEvent) GetBtc() *proto1.BTCEvent {
	if x, ok := m.GetEvent().(*ChainEvent_Btc); ok {
		return x.Btc
	}
	return nil
}

func (m *ChainEvent) GetValidator() *proto1.ValidatorEvent {
	if x, ok := m.GetEvent().(*ChainEvent_Validator); ok {
		return x.Validator
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ChainEvent) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ChainEvent_Builtin)(nil),
		(*ChainEvent_Erc20)(nil),
		(*ChainEvent_Btc)(nil),
		(*ChainEvent_Validator)(nil),
	}
}

func init() {
	proto.RegisterEnum("wallet.vega.commands.v1.NodeSignatureKind", NodeSignatureKind_name, NodeSignatureKind_value)
	proto.RegisterType((*NodeRegistration)(nil), "wallet.vega.commands.v1.NodeRegistration")
	proto.RegisterType((*NodeVote)(nil), "wallet.vega.commands.v1.NodeVote")
	proto.RegisterType((*NodeSignature)(nil), "wallet.vega.commands.v1.NodeSignature")
	proto.RegisterType((*ChainEvent)(nil), "wallet.vega.commands.v1.ChainEvent")
}

func init() {
	proto.RegisterFile("proto/commands/v1/validator_commands.proto", fileDescriptor_3bd0a30d86c3d00b)
}

var fileDescriptor_3bd0a30d86c3d00b = []byte{
	// 536 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xdd, 0x6e, 0xd3, 0x30,
	0x1c, 0xc5, 0x97, 0x6c, 0x6d, 0xe9, 0x7f, 0x6c, 0x2a, 0x06, 0xb4, 0x68, 0x08, 0x5a, 0xca, 0x2e,
	0xaa, 0x4a, 0x4b, 0xba, 0x22, 0x21, 0xa1, 0x21, 0xa4, 0x7e, 0x04, 0x16, 0x15, 0x85, 0x91, 0x76,
	0x2b, 0xe2, 0x26, 0xca, 0x87, 0xc9, 0xac, 0xa6, 0x76, 0x49, 0xdc, 0x76, 0x7b, 0x00, 0x1e, 0x82,
	0xa7, 0x43, 0xe2, 0x8e, 0x8f, 0x87, 0x40, 0x71, 0x96, 0x56, 0xd1, 0x98, 0xb8, 0x4b, 0x7c, 0x7e,
	0xe7, 0x9c, 0xbf, 0x2d, 0x1b, 0x9a, 0xb3, 0x88, 0x71, 0xa6, 0x79, 0x6c, 0x3a, 0x75, 0xa8, 0x1f,
	0x6b, 0x8b, 0x23, 0x6d, 0xe1, 0x84, 0xc4, 0x77, 0x38, 0x8b, 0xec, 0x6c, 0x55, 0x15, 0x10, 0xda,
	0x5b, 0x3a, 0x61, 0x88, 0xb9, 0xba, 0xc0, 0x81, 0xa3, 0xae, 0xb4, 0xc5, 0xd1, 0xbe, 0x72, 0x1d,
	0x72, 0xe1, 0x10, 0x6a, 0xe3, 0x05, 0xa6, 0xfc, 0xda, 0xb2, 0xff, 0x22, 0x20, 0xfc, 0x62, 0xee,
	0x26, 0xb4, 0x36, 0x5d, 0x12, 0x3e, 0x61, 0x4b, 0x2d, 0x60, 0x87, 0x42, 0x3c, 0x5c, 0x15, 0xc5,
	0xeb, 0xce, 0xd4, 0x57, 0xb7, 0xa1, 0x62, 0x32, 0x1f, 0x5b, 0x38, 0x20, 0x31, 0x8f, 0x1c, 0x4e,
	0x18, 0x45, 0x55, 0x28, 0xcd, 0xe6, 0xae, 0x3d, 0xc1, 0x57, 0x8a, 0x54, 0x93, 0x1a, 0x77, 0xbb,
	0xc5, 0x1f, 0xdf, 0xab, 0xf2, 0x47, 0xc9, 0x2a, 0xce, 0xe6, 0xee, 0x00, 0x5f, 0xa1, 0x26, 0xec,
	0xa4, 0x23, 0x64, 0x98, 0x9c, 0xc3, 0xb6, 0x85, 0x78, 0x2a, 0xd8, 0xfa, 0x07, 0xb8, 0x93, 0x14,
	0x9c, 0x33, 0x8e, 0xff, 0x1f, 0x7c, 0x00, 0xe5, 0x08, 0x7f, 0xc6, 0x11, 0xa6, 0x1e, 0x16, 0xa1,
	0xe5, 0x15, 0xb2, 0x16, 0xea, 0x5f, 0x60, 0x27, 0x89, 0x1c, 0x92, 0x80, 0x3a, 0x7c, 0x1e, 0x61,
	0xb4, 0x0b, 0x32, 0xf1, 0x45, 0x64, 0xd9, 0x92, 0x89, 0x8f, 0x2a, 0xb0, 0x19, 0x93, 0x20, 0x9d,
	0xca, 0x4a, 0x3e, 0xd1, 0x6b, 0xd8, 0x9a, 0x10, 0xea, 0x2b, 0x9b, 0x35, 0xa9, 0xb1, 0xdb, 0x6e,
	0xaa, 0xb7, 0x1c, 0xb0, 0x9a, 0xcb, 0x1d, 0x10, 0xea, 0x5b, 0xc2, 0x57, 0xff, 0x26, 0x03, 0xf4,
	0x92, 0x5d, 0xe9, 0xc9, 0xa1, 0xa3, 0xfb, 0x50, 0xe0, 0x97, 0xf6, 0xaa, 0x73, 0x8b, 0x5f, 0x1a,
	0x3e, 0x7a, 0x00, 0x05, 0xca, 0xb2, 0xc1, 0xb7, 0xac, 0xf4, 0x07, 0x1d, 0x43, 0xc9, 0x9d, 0x93,
	0x90, 0x13, 0xaa, 0xfc, 0x2c, 0xd5, 0xa4, 0xc6, 0x76, 0xfb, 0x49, 0xae, 0xbd, 0x9b, 0x8a, 0x9d,
	0x38, 0xc6, 0x5c, 0x84, 0x9f, 0x6c, 0x58, 0x99, 0x03, 0xb5, 0xa0, 0x80, 0x23, 0xaf, 0xdd, 0x52,
	0x7e, 0xa5, 0xd6, 0xbd, 0x9c, 0x55, 0xb7, 0x7a, 0xed, 0x56, 0xe6, 0x49, 0x41, 0xd4, 0x84, 0x4d,
	0x97, 0x7b, 0xca, 0xef, 0x94, 0x7f, 0x98, 0xaf, 0x1a, 0xf5, 0x32, 0x3a, 0x81, 0xd0, 0x2b, 0x28,
	0xaf, 0xae, 0x83, 0xf2, 0x27, 0x75, 0x3c, 0xca, 0x39, 0xce, 0x33, 0x39, 0xf3, 0xad, 0x0d, 0xdd,
	0x12, 0x14, 0xc4, 0x0d, 0x6c, 0x7e, 0x95, 0xe0, 0xde, 0x8d, 0x73, 0x43, 0xcf, 0xa0, 0x6a, 0xbe,
	0xef, 0xeb, 0xf6, 0xd0, 0x78, 0x6b, 0x76, 0x46, 0x67, 0x96, 0x6e, 0x0f, 0x0c, 0xb3, 0x6f, 0x9f,
	0x99, 0xc3, 0x53, 0xbd, 0x67, 0xbc, 0x31, 0xf4, 0x7e, 0x65, 0x03, 0x3d, 0x85, 0xc7, 0xff, 0x82,
	0x3a, 0xc3, 0xa1, 0x3e, 0xb2, 0x4d, 0x7d, 0x5c, 0x91, 0x50, 0x03, 0x0e, 0x6e, 0x47, 0xc6, 0xc6,
	0xe8, 0xa4, 0x6f, 0x75, 0xc6, 0x9d, 0x77, 0x15, 0xb9, 0x7b, 0xfc, 0xe9, 0xa5, 0xc7, 0x7c, 0x2c,
	0x26, 0x17, 0x97, 0xdb, 0x63, 0xa1, 0x4a, 0x58, 0xf2, 0x0c, 0xd2, 0x3d, 0x69, 0x84, 0x72, 0x1c,
	0x51, 0x27, 0xd4, 0x6e, 0xbc, 0x45, 0xb7, 0x28, 0x96, 0x9e, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff,
	0x46, 0x4d, 0xd6, 0xfe, 0xa7, 0x03, 0x00, 0x00,
}
