name: Add issue to team board

on:
  issues:
    types:
      - opened

jobs:
  add-to-team-board:
    runs-on: ubuntu-latest
    name: Add issue to Core team board
    steps:
      - uses: alex-page/github-project-automation-plus@50502d399cbb98cefe7ce1f99f93f78c6756562e
        with:
          project: Core (Team Board)
          column: Incoming to triage
          repo-token: ${{ secrets.GH_NEW_CARD_TO_PROJECT }}
