name: Label issues

on:
  issues:
    types:
      - opened

jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add "wallet" label
        uses: andymckay/labeler@5c59dabdfd4dd5bd9c6e6d255b01b9d764af4414
        with:
          add-labels: "wallet"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
