name: Search for code offences

on:
  push:
    tags:
      - v*
    branches:
      - master
      - develop
  pull_request:

jobs:
  golangci:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@5c56cd6c9dc07901af25baab6f2b0d9f3b7c3018 # hash of v2.5.2
        with:
          version: v1.42.1
