name: Verify CHANGELOG is updated

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  changelog-checker:
    if: startsWith(github.head_ref, 'renovate/') != true
    name: Run changelog-checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Changelog checker
        uses: Zomzog/changelog-checker@v1.2.0
        with:
          fileName: CHANGELOG.md
          #noChangelogLabel: my custom label # default `no changelog`
          checkNotification: Simple
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
