name: Verify PR has a linked issue

on:
  pull_request:
    types:
      - edited
      - synchronize
      - opened
      - reopened
  check_run:

jobs:
  verify-linked-issue:
    if: startsWith(github.head_ref, 'renovate/') != true
    runs-on: ubuntu-latest
    name: Ensure Pull Request has a linked issue.
    steps:
      - name: Verify Linked Issue
        uses: hattan/verify-linked-issue-action@2d8e2e47a462cc7b07ba5e6cab6f9d57bd36672e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
